package com.haihoo.ws.cxf.web.soap.userService2WS;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.16
 * 2018-07-17T23:51:50.712+08:00
 * Generated source version: 3.0.16
 * 
 */
@WebService(targetNamespace = "http://server2.cxf.web.baihoo.com/", name = "UserService2")
@XmlSeeAlso({ObjectFactory.class})
public interface UserService2 {

    @WebMethod
    @RequestWrapper(localName = "setUser", targetNamespace = "http://server2.cxf.web.baihoo.com/", className = "com.haihoo.ws.cxf.web.soap.userService2WS.SetUser")
    @ResponseWrapper(localName = "setUserResponse", targetNamespace = "http://server2.cxf.web.baihoo.com/", className = "com.haihoo.ws.cxf.web.soap.userService2WS.SetUserResponse")
    public void setUser(
        @WebParam(name = "arg0", targetNamespace = "")
        com.haihoo.ws.cxf.web.soap.userService2WS.User arg0
    );

    @WebMethod
    @RequestWrapper(localName = "getUserByName", targetNamespace = "http://server2.cxf.web.baihoo.com/", className = "com.haihoo.ws.cxf.web.soap.userService2WS.GetUserByName")
    @ResponseWrapper(localName = "getUserByNameResponse", targetNamespace = "http://server2.cxf.web.baihoo.com/", className = "com.haihoo.ws.cxf.web.soap.userService2WS.GetUserByNameResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.haihoo.ws.cxf.web.soap.userService2WS.User getUserByName(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
