package com.haihoo.ws.cxf.soap12.helloWS;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.16
 * 2018-07-17T20:52:23.557+08:00
 * Generated source version: 3.0.16
 * 
 */
@WebServiceClient(name = "HelloServerImplService", 
                  wsdlLocation = "http://127.0.0.1:8897/hello?wsdl",
                  targetNamespace = "http://soap12.server.cxf.ws.haihoo.com/") 
public class HelloServerImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://soap12.server.cxf.ws.haihoo.com/", "HelloServerImplService");
    public final static QName HelloServerImplPort = new QName("http://soap12.server.cxf.ws.haihoo.com/", "HelloServerImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://127.0.0.1:8897/hello?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(HelloServerImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://127.0.0.1:8897/hello?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public HelloServerImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public HelloServerImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HelloServerImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public HelloServerImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public HelloServerImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public HelloServerImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns HelloServerImpl
     */
    @WebEndpoint(name = "HelloServerImplPort")
    public HelloServerImpl getHelloServerImplPort() {
        return super.getPort(HelloServerImplPort, HelloServerImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HelloServerImpl
     */
    @WebEndpoint(name = "HelloServerImplPort")
    public HelloServerImpl getHelloServerImplPort(WebServiceFeature... features) {
        return super.getPort(HelloServerImplPort, HelloServerImpl.class, features);
    }

}
