/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.36
 * Generated at: 2018-07-29 15:08:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.EstConsole;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class defaultMain_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("    <!--开始Meta-->\n");
      out.write("    <meta charset=\"utf-8\"/>\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width,initial-scale=1.0\"/>\n");
      out.write("    <meta name=\"description\" content=\"\"/>\n");
      out.write("    <meta name=\"author\" content=\"ChenBaiHong\"/>\n");
      out.write("    <!--结束Meta-->\n");
      out.write("    <link rel=\"shortcut icon\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/backgroundPlug/img/\"/>\n");
      out.write("    <title>后台管理员操作界面</title>\n");
      out.write("    <!--开始引入css stylesheet-->\n");
      out.write("    <!-- BOOTSTRAP CSS -->\n");
      out.write("    <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/backgroundPlug/css/bootstrap.min.css\" rel=\"stylesheet\"/>\n");
      out.write("    <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/backgroundPlug/css/bootstrap-reset.css\" rel=\"stylesheet\"/>\n");
      out.write("    <!-- 特色风格的字体 图标 CSS样式 -->\n");
      out.write("    <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/backgroundPlug/assets/font-awesome/css/font-awesome.css\"rel=\"stylesheet\"/>\n");
      out.write("    <!-- 基本主题的 CSS 样式 -->\n");
      out.write("    <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/backgroundPlug/css/style.css\"rel=\"stylesheet\"/>\n");
      out.write("    <!--响应式主题css响应样式-->\n");
      out.write("    <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/backgroundPlug/css/style-responsive.css\" rel=\"stylesheet\"/>\n");
      out.write("    <!-- MORRIS 图表 CSS 样式 -->\n");
      out.write("    <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/backgroundPlug/assets/morris.js-0.4.3/morris.css\"rel=\"stylesheet\"/>\n");
      out.write("    <!--仪表盘 万年历 日历样式-->\n");
      out.write("    <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/backgroundPlug/css/clndr.css\" rel=\"stylesheet\">\n");
      out.write("\n");
      out.write("    <!--结束引入css stylesheet-->\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("    <!--开始页面包装-->\n");
      out.write("    <section class=\"wrapper\">\n");
      out.write("\t\t<!-- BEGIN ROW  -->\n");
      out.write("          <div class=\"row state-overview\">\n");
      out.write("            <div class=\"col-lg-3 col-sm-6\">\n");
      out.write("              <section class=\"panel\">\n");
      out.write("                <div class=\"symbol\">\n");
      out.write("                  <i class=\"fa fa-tags blue\">\n");
      out.write("                  </i>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"value\">\n");
      out.write("                  <h1 class=\"count\">\n");
      out.write("                    0\n");
      out.write("                  </h1>\n");
      out.write("                  <p>\n");
      out.write("                    总销售额\n");
      out.write("                  </p>\n");
      out.write("                </div>\n");
      out.write("              </section>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"col-lg-3 col-sm-6\">\n");
      out.write("              <section class=\"panel\">\n");
      out.write("                <div class=\"symbol\">\n");
      out.write("                  <i class=\"fa fa-money red\">\n");
      out.write("                  </i>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"value\">\n");
      out.write("                  <h1 class=\" count2\">\n");
      out.write("                    0\n");
      out.write("                  </h1>\n");
      out.write("                  <p>\n");
      out.write("                    总盈利\n");
      out.write("                  </p>\n");
      out.write("                </div>\n");
      out.write("              </section>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"col-lg-3 col-sm-6\">\n");
      out.write("              <section class=\"panel\">\n");
      out.write("                <div class=\"symbol\">\n");
      out.write("                  <i class=\"fa fa-user yellow\">\n");
      out.write("                  </i>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"value\">\n");
      out.write("                  <h1 class=\" count3\">\n");
      out.write("                    0\n");
      out.write("                  </h1>\n");
      out.write("                  <p>\n");
      out.write("                    新客户\n");
      out.write("                  </p>\n");
      out.write("                </div>\n");
      out.write("              </section>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"col-lg-3 col-sm-6\">\n");
      out.write("              <section class=\"panel\">\n");
      out.write("                <div class=\"symbol\">\n");
      out.write("                  <i class=\"fa fa-shopping-cart purple\">\n");
      out.write("                  </i>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"value\">\n");
      out.write("                  <h1 class=\" count4\">\n");
      out.write("                    0\n");
      out.write("                  </h1>\n");
      out.write("                  <p>\n");
      out.write("                    新订单\n");
      out.write("                  </p>\n");
      out.write("                </div>\n");
      out.write("              </section>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("\t\t   <!-- END ROW  -->\n");
      out.write("          <div id=\"morris\">\n");
      out.write("\t\t     <!-- BEGIN ROW  -->\n");
      out.write("            <div class=\"row\">\n");
      out.write("              <div class=\"col-lg-4\">\n");
      out.write("                <div class=\"panel terques-chart\">\n");
      out.write("                  <div class=\"panel-body chart-texture\">\n");
      out.write("                    <div class=\"chart\">\n");
      out.write("                      <div class=\"heading\">\n");
      out.write("                        <span>\n");
      out.write("                          Friday\n");
      out.write("                        </span>\n");
      out.write("                        <strong>\n");
      out.write("                          ￥ 657,00 | 55%\n");
      out.write("                        </strong>\n");
      out.write("                      </div>\n");
      out.write("                      <div class=\"sparkline\" data-type=\"line\" data-resize=\"true\" data-height=\"75\" data-width=\"90%\" data-line-width=\"1\" data-line-color=\"#fff\" data-spot-color=\"#fff\" data-fill-color=\"\" data-highlight-line-color=\"#fff\" data-spot-radius=\"4\" data-data=\"[564,123,890,564,455,200,135,667,333,526,996]\">\n");
      out.write("                      </div>\n");
      out.write("                    </div>\n");
      out.write("                  </div>\n");
      out.write("                  <div class=\"chart-tittle\">\n");
      out.write("                    <span class=\"title\">\n");
      out.write("                      最新收益\n");
      out.write("                    </span>\n");
      out.write("                    <span class=\"value\">\n");
      out.write("                      <a href=\"#\" class=\"active\">\n");
      out.write("                        Market\n");
      out.write("                      </a>\n");
      out.write("                      |\n");
      out.write("                      <a href=\"#\">\n");
      out.write("                        Local\n");
      out.write("                      </a>\n");
      out.write("                      |\n");
      out.write("                      <a href=\"#\">\n");
      out.write("                        Online\n");
      out.write("                      </a>\n");
      out.write("                    </span>\n");
      out.write("                  </div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"panel green-chart\">\n");
      out.write("                  <div class=\"panel-body\">\n");
      out.write("                    <div class=\"chart\">\n");
      out.write("                      <div class=\"heading\">\n");
      out.write("                        <span>\n");
      out.write("                          June\n");
      out.write("                        </span>\n");
      out.write("                        <strong>\n");
      out.write("                          23 Days | 65%\n");
      out.write("                        </strong>\n");
      out.write("                      </div>\n");
      out.write("                      <div id=\"designchart\">\n");
      out.write("                      </div>\n");
      out.write("                    </div>\n");
      out.write("                  </div>\n");
      out.write("                  <div class=\"chart-tittle\">\n");
      out.write("                    <span class=\"title\">\n");
      out.write("                      总收益\n");
      out.write("                    </span>\n");
      out.write("                    <span class=\"value\">\n");
      out.write("                      ￥, 50,23,561\n");
      out.write("                    </span>\n");
      out.write("                  </div>\n");
      out.write("                </div>\n");
      out.write("              </div>\n");
      out.write("              <div class=\"col-lg-2\">\n");
      out.write("                <div class=\"tiles facebook-tile text-center\">\n");
      out.write("                  <i class=\"fa fa-github icon-lg-size\">\n");
      out.write("                  </i>\n");
      out.write("                  <h4>\n");
      out.write("                    <a href=\"#fakelink\">\n");
      out.write("                      10K likes\n");
      out.write("                    </a>\n");
      out.write("                  </h4>\n");
      out.write("                </div>\n");
      out.write("                <!-- /.tiles .facebook-tile -->\n");
      out.write("                <div class=\"tiles twitter-tile text-center\">\n");
      out.write("                  <i class=\"fa fa-linkedin-square icon-lg-size\">\n");
      out.write("                  </i>\n");
      out.write("                  <h4>\n");
      out.write("                    <a href=\"#fakelink\">\n");
      out.write("                      2K followers\n");
      out.write("                    </a>\n");
      out.write("                  </h4>\n");
      out.write("                </div>\n");
      out.write("                <!-- /.tiles .twitter-tile -->\n");
      out.write("              </div>\n");
      out.write("              <div class=\"col-lg-6\">\n");
      out.write("                <section class=\"panel\">\n");
      out.write("                  <header class=\"panel-heading\">\n");
      out.write("                    未来预盈利(RMB)\n");
      out.write("                  </header>\n");
      out.write("                  <div class=\"panel-body\">\n");
      out.write("                    <div id=\"hero-area\" class=\"graph\">\n");
      out.write("                    </div>\n");
      out.write("                  </div>\n");
      out.write("                </section>\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("\t\t\t <!-- END ROW  -->\n");
      out.write("          </div>\n");
      out.write("\t\t   <!-- BEGIN ROW  -->\n");
      out.write("          <div class=\"row\">\n");
      out.write("            <div class=\"col-lg-8\">\n");
      out.write("              <section class=\"panel\">\n");
      out.write("                <div class=\"panel-body\">\n");
      out.write("                  <a href=\"#\" class=\"task-thumb\">\n");
      out.write("                    <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/backgroundPlug/AddRole/images/8.jpg\" alt=\"\">\n");
      out.write("                  </a>\n");
      out.write("                  <div class=\"task-thumb-details\">\n");
      out.write("                    <h1>\n");
      out.write("                      <a href=\"#\">\n");
      out.write("                        Work Progress\n");
      out.write("                      </a>\n");
      out.write("                    </h1>\n");
      out.write("                    <p>\n");
      out.write("                      BaiHong Chen\n");
      out.write("                    </p>\n");
      out.write("                  </div>\n");
      out.write("                </div>\n");
      out.write("                <table class=\"table table-hover personal-task\">\n");
      out.write("                  <tbody>\n");
      out.write("                    <tr>\n");
      out.write("                      <td>\n");
      out.write("                        1\n");
      out.write("                      </td>\n");
      out.write("                      <td>\n");
      out.write("                        Target Revenue\n");
      out.write("                      </td>\n");
      out.write("                      <td>\n");
      out.write("                        <span class=\"badge bg-important\">\n");
      out.write("                          75%\n");
      out.write("                        </span>\n");
      out.write("                      </td>\n");
      out.write("                      <td>\n");
      out.write("                        <div id=\"work-progress1\">\n");
      out.write("                        </div>\n");
      out.write("                      </td>\n");
      out.write("                    </tr>\n");
      out.write("                    <tr>\n");
      out.write("                      <td>\n");
      out.write("                        2\n");
      out.write("                      </td>\n");
      out.write("                      <td>\n");
      out.write("                        Project Larsen\n");
      out.write("                      </td>\n");
      out.write("                      <td>\n");
      out.write("                        <span class=\"badge bg-success\">\n");
      out.write("                          43%\n");
      out.write("                        </span>\n");
      out.write("                      </td>\n");
      out.write("                      <td>\n");
      out.write("                        <div id=\"work-progress2\">\n");
      out.write("                        </div>\n");
      out.write("                      </td>\n");
      out.write("                    </tr>\n");
      out.write("                    <tr>\n");
      out.write("                      <td>\n");
      out.write("                        3\n");
      out.write("                      </td>\n");
      out.write("                      <td>\n");
      out.write("                        Project Nowbie\n");
      out.write("                      </td>\n");
      out.write("                      <td>\n");
      out.write("                        <span class=\"badge bg-info\">\n");
      out.write("                          67%\n");
      out.write("                        </span>\n");
      out.write("                      </td>\n");
      out.write("                      <td>\n");
      out.write("                        <div id=\"work-progress3\">\n");
      out.write("                        </div>\n");
      out.write("                      </td>\n");
      out.write("                    </tr>\n");
      out.write("                    <tr>\n");
      out.write("                      <td>\n");
      out.write("                        4\n");
      out.write("                      </td>\n");
      out.write("                      <td>\n");
      out.write("                        Total Sales\n");
      out.write("                      </td>\n");
      out.write("                      <td>\n");
      out.write("                        <span class=\"badge bg-warning\">\n");
      out.write("                          30%\n");
      out.write("                        </span>\n");
      out.write("                      </td>\n");
      out.write("                      <td>\n");
      out.write("                        <div id=\"work-progress4\">\n");
      out.write("                        </div>\n");
      out.write("                      </td>\n");
      out.write("                    </tr>\n");
      out.write("                    <tr>\n");
      out.write("                      <td>\n");
      out.write("                        5\n");
      out.write("                      </td>\n");
      out.write("                      <td>\n");
      out.write("                        Delivery Pending\n");
      out.write("                      </td>\n");
      out.write("                      <td>\n");
      out.write("                        <span class=\"badge bg-primary\">\n");
      out.write("                          15%\n");
      out.write("                        </span>\n");
      out.write("                      </td>\n");
      out.write("                      <td>\n");
      out.write("                        <div id=\"work-progress5\">\n");
      out.write("                        </div>\n");
      out.write("                      </td>\n");
      out.write("                    </tr>\n");
      out.write("                  </tbody>\n");
      out.write("                </table>\n");
      out.write("              </section>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"col-lg-4\">\n");
      out.write("              <section class=\"panel post-wrap pro-box\">\n");
      out.write("                <aside>\n");
      out.write("                  <div class=\"post-info\">\n");
      out.write("                    <div class=\"panel-body\">\n");
      out.write("                      <footer class=\"social-footer\">\n");
      out.write("                        <ul>\n");
      out.write("                          <li class=\"active\">\n");
      out.write("                            <a href=\"#\">\n");
      out.write("                              <i class=\"fa  fa-github-square\">\n");
      out.write("                              </i>\n");
      out.write("                            </a>\n");
      out.write("                          </li>\n");
      out.write("                        </ul>\n");
      out.write("                      </footer>\n");
      out.write("                      <!-- END  FOOTER -->\n");
      out.write("                      <div class=\"text-center twite\">\n");
      out.write("                        <h1>\n");
      out.write("                          We just Launch a New Theme Check it Out at\n");
      out.write("                          <a href=\"javascript:;\">\n");
      out.write("                            http://www.ChenBaiHong.gitHub.com/\n");
      out.write("                          </a>\n");
      out.write("                        </h1>\n");
      out.write("                        <p >\n");
      out.write("                          4 Days ago\n");
      out.write("                        </p>\n");
      out.write("                      </div>\n");
      out.write("                    </div>\n");
      out.write("                  </div>\n");
      out.write("                </aside>\n");
      out.write("              </section>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("\t\t   <!-- END ROW  -->\n");
      out.write("\t\t    <!-- BEGIN ROW  -->\n");
      out.write("          <div class=\"row\">\n");
      out.write("            <div class=\"col-lg-6\">\n");
      out.write("              <div class=\"panel\">\n");
      out.write("                <div class=\"panel-body\">\n");
      out.write("                  <div class=\"media usr-info\">\n");
      out.write("                    <a href=\"#\" class=\"pull-left\">\n");
      out.write("                      <img class=\"thumb\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/backgroundPlug/AddRole/images/8.jpg\" alt=\"\">\n");
      out.write("                    </a>\n");
      out.write("                    <div class=\"media-body\">\n");
      out.write("                      <h4 class=\"media-heading\">\n");
      out.write("                        BaiHong Chen\n");
      out.write("                      </h4>\n");
      out.write("                      <span>\n");
      out.write("                        Chief-Sarathi\n");
      out.write("                      </span>\n");
      out.write("                      <p>\n");
      out.write("                        I handcraft beautiful websites and application for all kind of devices\n");
      out.write("                      </p>\n");
      out.write("                    </div>\n");
      out.write("                  </div>\n");
      out.write("                </div>\n");
      out.write("              </div>\n");
      out.write("              <section class=\"panel\">\n");
      out.write("                <div class=\"weather-bg\">\n");
      out.write("                  <div class=\"panel-body\">\n");
      out.write("                    <div class=\"row\">\n");
      out.write("                      <div class=\"col-xs-6\">\n");
      out.write("                        <i class=\"fa fa-cloud\">\n");
      out.write("                        </i>\n");
      out.write("                        成都\n");
      out.write("                      </div>\n");
      out.write("                      <div class=\"col-xs-6\">\n");
      out.write("                        <div class=\"degree\">\n");
      out.write("                          48°\n");
      out.write("                        </div>\n");
      out.write("                      </div>\n");
      out.write("                    </div>\n");
      out.write("                  </div>\n");
      out.write("                </div>\n");
      out.write("                <footer class=\"weather-category\">\n");
      out.write("                  <ul>\n");
      out.write("                    <li class=\"active\">\n");
      out.write("                      <h5>\n");
      out.write("                        湿度\n");
      out.write("                      </h5>\n");
      out.write("                      45%\n");
      out.write("                    </li>\n");
      out.write("                    <li>\n");
      out.write("                      <h5>\n");
      out.write("                        风力\n");
      out.write("                      </h5>\n");
      out.write("                      5 mph\n");
      out.write("                    </li>\n");
      out.write("                  </ul>\n");
      out.write("                </footer>\n");
      out.write("                <!-- END  FOOTER -->\n");
      out.write("              </section>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"col-lg-6\">\n");
      out.write("              <div class=\"panel\">\n");
      out.write("                <div class=\"panel-body\">\n");
      out.write("                  <div class=\"calendar-block \">\n");
      out.write("                    <div class=\"cal1\">\n");
      out.write("                    </div>\n");
      out.write("                  </div>\n");
      out.write("                </div>\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("\t\t   <!-- END ROW  -->\n");
      out.write("\t\t    <!-- BEGIN ROW  -->\n");
      out.write("          <div class=\"row\">\n");
      out.write("            <div class=\"col-lg-6\">\n");
      out.write("              <div class=\"panel\">\n");
      out.write("                <div class=\"panel-body\">\n");
      out.write("                  <footer class=\"project-category\">\n");
      out.write("                    <ul>\n");
      out.write("                      <li class=\"active\">\n");
      out.write("                        <h5>\n");
      out.write("                          才高八斗\n");
      out.write("                        </h5>\n");
      out.write("                        <div id=\"work-progress6\">\n");
      out.write("                        </div>\n");
      out.write("                      </li>\n");
      out.write("                      <li>\n");
      out.write("                        <h5>\n");
      out.write("                          风流倜傥\n");
      out.write("                        </h5>\n");
      out.write("                        <div id=\"work-progress7\">\n");
      out.write("                        </div>\n");
      out.write("                      </li>\n");
      out.write("                      <li>\n");
      out.write("                        <h5>\n");
      out.write("                          翩翩君子\n");
      out.write("                        </h5>\n");
      out.write("                        <div id=\"work-progress8\">\n");
      out.write("                        </div>\n");
      out.write("                      </li>\n");
      out.write("                    </ul>\n");
      out.write("                    <h1>\n");
      out.write("                      柏宏 评价\n");
      out.write("                    </h1>\n");
      out.write("                  </footer>\n");
      out.write("                  <!-- END  FOOTER -->\n");
      out.write("                </div>\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"col-lg-6\">\n");
      out.write("              <div class=\"panel\">\n");
      out.write("                <div class=\"panel-body\">\n");
      out.write("                  <div class=\"bio-chart\">\n");
      out.write("                    <input class=\"knob\" data-width=\"100\" data-height=\"100\" data-displayPrevious=true data-thickness=\".2\" value=\"78\" data-fgColor=\"#f9a3a3\" data-bgColor=\"#e8e8e8\">\n");
      out.write("                    <h4 class=\"red\">\n");
      out.write("                      Profit\n");
      out.write("                    </h4>\n");
      out.write("                  </div>\n");
      out.write("                  <div class=\"bio-chart\">\n");
      out.write("                    <input class=\"knob\" data-width=\"100\" data-height=\"100\" data-displayPrevious=true data-thickness=\".2\" value=\"63\" data-fgColor=\"#fcce54\" data-bgColor=\"#e8e8e8\">\n");
      out.write("                    <h4 class=\"yellow\">\n");
      out.write("                      Expansion \n");
      out.write("                    </h4>\n");
      out.write("                  </div>\n");
      out.write("                </div>\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("\t\t   <!-- END ROW  -->\n");
      out.write("    </section>\n");
      out.write("    <!--结束页面包装-->\n");
      out.write("    <!-- END MAIN CONTENT -->\n");
      out.write("      <!-- BEGIN FOOTER -->\n");
      out.write("      <footer class=\"site-footer\">\n");
      out.write("        <div class=\"text-center\">\n");
      out.write("          2016 &copy; BaiHong  \n");
      out.write("          <a href=\"\" target=\"_blank\">\n");
      out.write("            China Made\n");
      out.write("          </a>\n");
      out.write("          <a href=\"#\" class=\"go-top\">\n");
      out.write("            <i class=\"fa fa-angle-up\">\n");
      out.write("            </i>\n");
      out.write("          </a>\n");
      out.write("        </div>\n");
      out.write("      </footer>\n");
      out.write("      <!-- END  FOOTER -->\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/backgroundPlug/js/jquery.js\" ></script><!-- BASIC JQUERY 1.8.3 LIB. JS -->\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/backgroundPlug/js/bootstrap.min.js\" ></script><!-- BOOTSTRAP JS -->\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/backgroundPlug/js/jquery.dcjqaccordion.2.7.js\"></script><!-- ACCORDIN JS -->\n");
      out.write("<!-- SCROLLTO JS -->\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/backgroundPlug/js/jquery.nicescroll.js\" ></script><!-- NICESCROLL JS -->\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/backgroundPlug/js/respond.min.js\" ></script><!-- RESPOND JS -->\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/backgroundPlug/js/jquery.sparkline.js\"></script><!-- SPARKLINE JS -->\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/backgroundPlug/js/sparkline-chart.js\"></script><!-- SPARKLINE CHART JS -->\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/backgroundPlug/js/common-scripts.js\"></script><!-- BASIC COMMON JS -->\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/backgroundPlug/js/count.js\"></script><!-- COUNT JS -->\n");
      out.write("<!--Morris-->\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/backgroundPlug/assets/morris.js-0.4.3/morris.min.js\" ></script><!-- MORRIS JS -->\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/backgroundPlug/assets/morris.js-0.4.3/raphael-min.js\" ></script><!-- MORRIS  JS -->\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/backgroundPlug/assets/chart-master/Chart.js\" ></script>\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/backgroundPlug/js/chart.js\" ></script><!-- CHART JS -->\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/backgroundPlug/js/all-chartjs.js\" ></script><!-- MORRIS  JS -->\n");
      out.write("\n");
      out.write("<!--Calendar-->\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/backgroundPlug/js/calendar/clndr.js\"></script><!-- CALENDER JS -->\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/backgroundPlug/js/calendar/evnt.calendar.init.js\"></script><!-- CALENDER EVENT JS -->\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/backgroundPlug/js/calendar/moment-2.2.1.js\"></script><!-- CALENDER MOMENT JS -->\n");
      out.write("<script src=\"http://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.5.2/underscore-min.js\"></script><!-- UNDERSCORE JS -->\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/backgroundPlug/assets/jquery-knob/js/jquery.knob.js\" ></script><!-- JQUERY KNOB JS -->\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("    $(\".knob\").knob();\n");
      out.write("</script>\n");
      out.write("<!-- 结束引入js插件 -->\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
