CREATE TABLE `BH_MEMBER` (
  `ID` int(11) NOT NULL AUTO_INCREMENT COMMENT '组员唯一识别id',
  `ME_NAME` varchar(225) NOT NULL COMMENT '成员名称',
  `ME_AGE` int(11) DEFAULT NULL COMMENT '成员年纪',
  `ME_NO` varchar(32) DEFAULT NULL COMMENT '成员编号',
  `ME_DESC` varchar(656) DEFAULT NULL COMMENT '成员描述',
  `BIRTH_DATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '出生日期',
  `UPDATE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后更新时间',
  `CREATE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `VERSION` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;