/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.82
 * Generated at: 2018-07-29 14:57:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.webpage.com.jeecg.demo;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class logList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/tld/easyui.tld", Long.valueOf(1520613796042L));
    _jspx_dependants.put("/context/mytags.jsp", Long.valueOf(1520613796052L));
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ft_005fbase_0026_005ftype_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ft_005fdatagrid_0026_005ftitle_005fsortOrder_005fsortName_005fqueryMode_005fpageSize_005fname_005fidField_005fextendParams_005factionUrl;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ft_005fdgCol_0026_005ftitle_005freplace_005fquery_005ffield_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ft_005fdgCol_0026_005ftitle_005fhidden_005ffield_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ft_005fdgCol_0026_005fwidth_005ftitle_005ffield_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ft_005fdgCol_0026_005fwidth_005ftitle_005fqueryMode_005fquery_005fformatter_005ffield_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ft_005fdgToolBar_0026_005furl_005ftitle_005ficon_005ffunname_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ft_005fbase_0026_005ftype_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ft_005fdatagrid_0026_005ftitle_005fsortOrder_005fsortName_005fqueryMode_005fpageSize_005fname_005fidField_005fextendParams_005factionUrl = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ft_005fdgCol_0026_005ftitle_005freplace_005fquery_005ffield_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ft_005fdgCol_0026_005ftitle_005fhidden_005ffield_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ft_005fdgCol_0026_005fwidth_005ftitle_005ffield_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ft_005fdgCol_0026_005fwidth_005ftitle_005fqueryMode_005fquery_005fformatter_005ffield_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ft_005fdgToolBar_0026_005furl_005ftitle_005ficon_005ffunname_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005ft_005fbase_0026_005ftype_005fnobody.release();
    _005fjspx_005ftagPool_005ft_005fdatagrid_0026_005ftitle_005fsortOrder_005fsortName_005fqueryMode_005fpageSize_005fname_005fidField_005fextendParams_005factionUrl.release();
    _005fjspx_005ftagPool_005ft_005fdgCol_0026_005ftitle_005freplace_005fquery_005ffield_005fnobody.release();
    _005fjspx_005ftagPool_005ft_005fdgCol_0026_005ftitle_005fhidden_005ffield_005fnobody.release();
    _005fjspx_005ftagPool_005ft_005fdgCol_0026_005fwidth_005ftitle_005ffield_005fnobody.release();
    _005fjspx_005ftagPool_005ft_005fdgCol_0026_005fwidth_005ftitle_005fqueryMode_005fquery_005fformatter_005ffield_005fnobody.release();
    _005fjspx_005ftagPool_005ft_005fdgToolBar_0026_005furl_005ftitle_005ficon_005ffunname_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
 
String path = request.getContextPath();
String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path;

      out.write('\n');
      //  c:set
      org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
      boolean _jspx_th_c_005fset_005f0_reused = false;
      try {
        _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
        _jspx_th_c_005fset_005f0.setParent(null);
        // /context/mytags.jsp(9,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_c_005fset_005f0.setVar("webRoot");
        // /context/mytags.jsp(9,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
        _jspx_th_c_005fset_005f0.setValue(basePath);
        int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
        if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
        _jspx_th_c_005fset_005f0_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
      }
      out.write('\n');
      if (_jspx_meth_t_005fbase_005f0(_jspx_page_context))
        return;
      out.write('\n');
      if (_jspx_meth_t_005fdatagrid_005f0(_jspx_page_context))
        return;
      out.write('\n');
      out.write("\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("    $(document).ready(function(){\n");
      out.write("        $(\"input\").css(\"height\", \"24px\");\n");
      out.write("    });\n");
      out.write("    \n");
      out.write("    function logListsearch(){\n");
      out.write("    \tvar loglevel = $(\"#loglevel\").val();\n");
      out.write("    \tvar operatetime_begin = $(\"#operatetime_begin\").val();\n");
      out.write("    \tvar operatetime_end = $(\"#operatetime_end\").val();\n");
      out.write("    \tif(jQuery.trim(operatetime_begin) != '' || jQuery.trim(operatetime_end) != ''){\n");
      out.write("    \t\t$(\"#logList\").datagrid('load',{\n");
      out.write("        \t\tloglevel : loglevel,\n");
      out.write("        \t\toperatetime_begin : operatetime_begin,\n");
      out.write("        \t\toperatetime_end : operatetime_end\n");
      out.write("        \t});\n");
      out.write("    \t}else{\n");
      out.write("    \t\t$(\"#logList\").datagrid('load',{\n");
      out.write("        \t\tloglevel : loglevel\n");
      out.write("        \t});\n");
      out.write("    \t}\n");
      out.write("    }\n");
      out.write("    \n");
      out.write("    function clearSearch(){\n");
      out.write("    \t$(\"#loglevel\").val(0);\n");
      out.write("    \t$(\"#operatetime_begin\").val(\"\");\n");
      out.write("    \t$(\"#operatetime_end\").val(\"\");\n");
      out.write("    \t$(\"#logList\").datagrid('load',{});\n");
      out.write("    }\n");
      out.write("    \n");
      out.write("    function goBaobiao(title,addurl){\n");
      out.write("    \tcreatedetailwindow(title,addurl);\n");
      out.write("    }\n");
      out.write("    function goBaobiao2(title,addurl){\n");
      out.write("    \taddOneTab(title,addurl);\n");
      out.write("    }\n");
      out.write("</script>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_t_005fbase_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  t:base
    org.jeecgframework.tag.core.easyui.BaseTag _jspx_th_t_005fbase_005f0 = (org.jeecgframework.tag.core.easyui.BaseTag) _005fjspx_005ftagPool_005ft_005fbase_0026_005ftype_005fnobody.get(org.jeecgframework.tag.core.easyui.BaseTag.class);
    boolean _jspx_th_t_005fbase_005f0_reused = false;
    try {
      _jspx_th_t_005fbase_005f0.setPageContext(_jspx_page_context);
      _jspx_th_t_005fbase_005f0.setParent(null);
      // /webpage/com/jeecg/demo/logList.jsp(3,0) name = type type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_t_005fbase_005f0.setType("jquery,easyui,tools,DatePicker");
      int _jspx_eval_t_005fbase_005f0 = _jspx_th_t_005fbase_005f0.doStartTag();
      if (_jspx_th_t_005fbase_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ft_005fbase_0026_005ftype_005fnobody.reuse(_jspx_th_t_005fbase_005f0);
      _jspx_th_t_005fbase_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_t_005fbase_005f0, _jsp_getInstanceManager(), _jspx_th_t_005fbase_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_t_005fdatagrid_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  t:datagrid
    org.jeecgframework.tag.core.easyui.DataGridTag _jspx_th_t_005fdatagrid_005f0 = (org.jeecgframework.tag.core.easyui.DataGridTag) _005fjspx_005ftagPool_005ft_005fdatagrid_0026_005ftitle_005fsortOrder_005fsortName_005fqueryMode_005fpageSize_005fname_005fidField_005fextendParams_005factionUrl.get(org.jeecgframework.tag.core.easyui.DataGridTag.class);
    boolean _jspx_th_t_005fdatagrid_005f0_reused = false;
    try {
      _jspx_th_t_005fdatagrid_005f0.setPageContext(_jspx_page_context);
      _jspx_th_t_005fdatagrid_005f0.setParent(null);
      // /webpage/com/jeecg/demo/logList.jsp(4,0) name = title type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_t_005fdatagrid_005f0.setTitle("日志");
      // /webpage/com/jeecg/demo/logList.jsp(4,0) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_t_005fdatagrid_005f0.setName("logList");
      // /webpage/com/jeecg/demo/logList.jsp(4,0) name = actionUrl type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_t_005fdatagrid_005f0.setActionUrl("jeecgListDemoController.do?logDatagrid");
      // /webpage/com/jeecg/demo/logList.jsp(4,0) name = idField type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_t_005fdatagrid_005f0.setIdField("id");
      // /webpage/com/jeecg/demo/logList.jsp(4,0) name = sortName type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_t_005fdatagrid_005f0.setSortName("operatetime");
      // /webpage/com/jeecg/demo/logList.jsp(4,0) name = sortOrder type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_t_005fdatagrid_005f0.setSortOrder("desc");
      // /webpage/com/jeecg/demo/logList.jsp(4,0) name = queryMode type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_t_005fdatagrid_005f0.setQueryMode("group");
      // /webpage/com/jeecg/demo/logList.jsp(4,0) name = pageSize type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_t_005fdatagrid_005f0.setPageSize(500);
      // /webpage/com/jeecg/demo/logList.jsp(4,0) name = extendParams type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_t_005fdatagrid_005f0.setExtendParams("view:scrollview,");
      int _jspx_eval_t_005fdatagrid_005f0 = _jspx_th_t_005fdatagrid_005f0.doStartTag();
      if (_jspx_eval_t_005fdatagrid_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write('\n');
          out.write('	');
          if (_jspx_meth_t_005fdgCol_005f0(_jspx_th_t_005fdatagrid_005f0, _jspx_page_context))
            return true;
          out.write('\n');
          out.write('	');
          if (_jspx_meth_t_005fdgCol_005f1(_jspx_th_t_005fdatagrid_005f0, _jspx_page_context))
            return true;
          out.write('\n');
          out.write('	');
          if (_jspx_meth_t_005fdgCol_005f2(_jspx_th_t_005fdatagrid_005f0, _jspx_page_context))
            return true;
          out.write('\n');
          out.write('	');
          if (_jspx_meth_t_005fdgCol_005f3(_jspx_th_t_005fdatagrid_005f0, _jspx_page_context))
            return true;
          out.write('\n');
          out.write('	');
          if (_jspx_meth_t_005fdgCol_005f4(_jspx_th_t_005fdatagrid_005f0, _jspx_page_context))
            return true;
          out.write('\n');
          out.write('	');
          if (_jspx_meth_t_005fdgCol_005f5(_jspx_th_t_005fdatagrid_005f0, _jspx_page_context))
            return true;
          out.write('\n');
          out.write('	');
          if (_jspx_meth_t_005fdgCol_005f6(_jspx_th_t_005fdatagrid_005f0, _jspx_page_context))
            return true;
          out.write('\n');
          out.write('	');
          if (_jspx_meth_t_005fdgCol_005f7(_jspx_th_t_005fdatagrid_005f0, _jspx_page_context))
            return true;
          out.write("\n");
          out.write("\t\n");
          out.write("\t ");
          if (_jspx_meth_t_005fdgToolBar_005f0(_jspx_th_t_005fdatagrid_005f0, _jspx_page_context))
            return true;
          out.write('\n');
          out.write('	');
          out.write(' ');
          if (_jspx_meth_t_005fdgToolBar_005f1(_jspx_th_t_005fdatagrid_005f0, _jspx_page_context))
            return true;
          out.write("\n");
          out.write("   \t \n");
          int evalDoAfterBody = _jspx_th_t_005fdatagrid_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_t_005fdatagrid_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ft_005fdatagrid_0026_005ftitle_005fsortOrder_005fsortName_005fqueryMode_005fpageSize_005fname_005fidField_005fextendParams_005factionUrl.reuse(_jspx_th_t_005fdatagrid_005f0);
      _jspx_th_t_005fdatagrid_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_t_005fdatagrid_005f0, _jsp_getInstanceManager(), _jspx_th_t_005fdatagrid_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_t_005fdgCol_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_t_005fdatagrid_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  t:dgCol
    org.jeecgframework.tag.core.easyui.DataGridColumnTag _jspx_th_t_005fdgCol_005f0 = (org.jeecgframework.tag.core.easyui.DataGridColumnTag) _005fjspx_005ftagPool_005ft_005fdgCol_0026_005ftitle_005freplace_005fquery_005ffield_005fnobody.get(org.jeecgframework.tag.core.easyui.DataGridColumnTag.class);
    boolean _jspx_th_t_005fdgCol_005f0_reused = false;
    try {
      _jspx_th_t_005fdgCol_005f0.setPageContext(_jspx_page_context);
      _jspx_th_t_005fdgCol_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_t_005fdatagrid_005f0);
      // /webpage/com/jeecg/demo/logList.jsp(6,1) name = title type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_t_005fdgCol_005f0.setTitle("log.level");
      // /webpage/com/jeecg/demo/logList.jsp(6,1) name = field type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_t_005fdgCol_005f0.setField("loglevel");
      // /webpage/com/jeecg/demo/logList.jsp(6,1) name = query type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_t_005fdgCol_005f0.setQuery(true);
      // /webpage/com/jeecg/demo/logList.jsp(6,1) name = replace type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_t_005fdgCol_005f0.setReplace("登录_1,退出_2,插入_3,删除_4,修改_5,上传_6,其他_7");
      int _jspx_eval_t_005fdgCol_005f0 = _jspx_th_t_005fdgCol_005f0.doStartTag();
      if (_jspx_th_t_005fdgCol_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ft_005fdgCol_0026_005ftitle_005freplace_005fquery_005ffield_005fnobody.reuse(_jspx_th_t_005fdgCol_005f0);
      _jspx_th_t_005fdgCol_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_t_005fdgCol_005f0, _jsp_getInstanceManager(), _jspx_th_t_005fdgCol_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_t_005fdgCol_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_t_005fdatagrid_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  t:dgCol
    org.jeecgframework.tag.core.easyui.DataGridColumnTag _jspx_th_t_005fdgCol_005f1 = (org.jeecgframework.tag.core.easyui.DataGridColumnTag) _005fjspx_005ftagPool_005ft_005fdgCol_0026_005ftitle_005fhidden_005ffield_005fnobody.get(org.jeecgframework.tag.core.easyui.DataGridColumnTag.class);
    boolean _jspx_th_t_005fdgCol_005f1_reused = false;
    try {
      _jspx_th_t_005fdgCol_005f1.setPageContext(_jspx_page_context);
      _jspx_th_t_005fdgCol_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_t_005fdatagrid_005f0);
      // /webpage/com/jeecg/demo/logList.jsp(7,1) name = title type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_t_005fdgCol_005f1.setTitle("common.id");
      // /webpage/com/jeecg/demo/logList.jsp(7,1) name = field type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_t_005fdgCol_005f1.setField("id");
      // /webpage/com/jeecg/demo/logList.jsp(7,1) name = hidden type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_t_005fdgCol_005f1.setHidden(true);
      int _jspx_eval_t_005fdgCol_005f1 = _jspx_th_t_005fdgCol_005f1.doStartTag();
      if (_jspx_th_t_005fdgCol_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ft_005fdgCol_0026_005ftitle_005fhidden_005ffield_005fnobody.reuse(_jspx_th_t_005fdgCol_005f1);
      _jspx_th_t_005fdgCol_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_t_005fdgCol_005f1, _jsp_getInstanceManager(), _jspx_th_t_005fdgCol_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_t_005fdgCol_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_t_005fdatagrid_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  t:dgCol
    org.jeecgframework.tag.core.easyui.DataGridColumnTag _jspx_th_t_005fdgCol_005f2 = (org.jeecgframework.tag.core.easyui.DataGridColumnTag) _005fjspx_005ftagPool_005ft_005fdgCol_0026_005fwidth_005ftitle_005ffield_005fnobody.get(org.jeecgframework.tag.core.easyui.DataGridColumnTag.class);
    boolean _jspx_th_t_005fdgCol_005f2_reused = false;
    try {
      _jspx_th_t_005fdgCol_005f2.setPageContext(_jspx_page_context);
      _jspx_th_t_005fdgCol_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_t_005fdatagrid_005f0);
      // /webpage/com/jeecg/demo/logList.jsp(8,1) name = title type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_t_005fdgCol_005f2.setTitle("log.content");
      // /webpage/com/jeecg/demo/logList.jsp(8,1) name = field type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_t_005fdgCol_005f2.setField("logcontent");
      // /webpage/com/jeecg/demo/logList.jsp(8,1) name = width type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_t_005fdgCol_005f2.setWidth(new java.lang.Integer(340));
      int _jspx_eval_t_005fdgCol_005f2 = _jspx_th_t_005fdgCol_005f2.doStartTag();
      if (_jspx_th_t_005fdgCol_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ft_005fdgCol_0026_005fwidth_005ftitle_005ffield_005fnobody.reuse(_jspx_th_t_005fdgCol_005f2);
      _jspx_th_t_005fdgCol_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_t_005fdgCol_005f2, _jsp_getInstanceManager(), _jspx_th_t_005fdgCol_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_t_005fdgCol_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_t_005fdatagrid_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  t:dgCol
    org.jeecgframework.tag.core.easyui.DataGridColumnTag _jspx_th_t_005fdgCol_005f3 = (org.jeecgframework.tag.core.easyui.DataGridColumnTag) _005fjspx_005ftagPool_005ft_005fdgCol_0026_005fwidth_005ftitle_005ffield_005fnobody.get(org.jeecgframework.tag.core.easyui.DataGridColumnTag.class);
    boolean _jspx_th_t_005fdgCol_005f3_reused = false;
    try {
      _jspx_th_t_005fdgCol_005f3.setPageContext(_jspx_page_context);
      _jspx_th_t_005fdgCol_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_t_005fdatagrid_005f0);
      // /webpage/com/jeecg/demo/logList.jsp(9,1) name = title type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_t_005fdgCol_005f3.setTitle("operate.ip");
      // /webpage/com/jeecg/demo/logList.jsp(9,1) name = field type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_t_005fdgCol_005f3.setField("note");
      // /webpage/com/jeecg/demo/logList.jsp(9,1) name = width type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_t_005fdgCol_005f3.setWidth(new java.lang.Integer(200));
      int _jspx_eval_t_005fdgCol_005f3 = _jspx_th_t_005fdgCol_005f3.doStartTag();
      if (_jspx_th_t_005fdgCol_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ft_005fdgCol_0026_005fwidth_005ftitle_005ffield_005fnobody.reuse(_jspx_th_t_005fdgCol_005f3);
      _jspx_th_t_005fdgCol_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_t_005fdgCol_005f3, _jsp_getInstanceManager(), _jspx_th_t_005fdgCol_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_t_005fdgCol_005f4(javax.servlet.jsp.tagext.JspTag _jspx_th_t_005fdatagrid_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  t:dgCol
    org.jeecgframework.tag.core.easyui.DataGridColumnTag _jspx_th_t_005fdgCol_005f4 = (org.jeecgframework.tag.core.easyui.DataGridColumnTag) _005fjspx_005ftagPool_005ft_005fdgCol_0026_005fwidth_005ftitle_005ffield_005fnobody.get(org.jeecgframework.tag.core.easyui.DataGridColumnTag.class);
    boolean _jspx_th_t_005fdgCol_005f4_reused = false;
    try {
      _jspx_th_t_005fdgCol_005f4.setPageContext(_jspx_page_context);
      _jspx_th_t_005fdgCol_005f4.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_t_005fdatagrid_005f0);
      // /webpage/com/jeecg/demo/logList.jsp(10,1) name = title type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_t_005fdgCol_005f4.setTitle("操作人ID");
      // /webpage/com/jeecg/demo/logList.jsp(10,1) name = field type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_t_005fdgCol_005f4.setField("TSUser.userName");
      // /webpage/com/jeecg/demo/logList.jsp(10,1) name = width type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_t_005fdgCol_005f4.setWidth(new java.lang.Integer(200));
      int _jspx_eval_t_005fdgCol_005f4 = _jspx_th_t_005fdgCol_005f4.doStartTag();
      if (_jspx_th_t_005fdgCol_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ft_005fdgCol_0026_005fwidth_005ftitle_005ffield_005fnobody.reuse(_jspx_th_t_005fdgCol_005f4);
      _jspx_th_t_005fdgCol_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_t_005fdgCol_005f4, _jsp_getInstanceManager(), _jspx_th_t_005fdgCol_005f4_reused);
    }
    return false;
  }

  private boolean _jspx_meth_t_005fdgCol_005f5(javax.servlet.jsp.tagext.JspTag _jspx_th_t_005fdatagrid_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  t:dgCol
    org.jeecgframework.tag.core.easyui.DataGridColumnTag _jspx_th_t_005fdgCol_005f5 = (org.jeecgframework.tag.core.easyui.DataGridColumnTag) _005fjspx_005ftagPool_005ft_005fdgCol_0026_005fwidth_005ftitle_005ffield_005fnobody.get(org.jeecgframework.tag.core.easyui.DataGridColumnTag.class);
    boolean _jspx_th_t_005fdgCol_005f5_reused = false;
    try {
      _jspx_th_t_005fdgCol_005f5.setPageContext(_jspx_page_context);
      _jspx_th_t_005fdgCol_005f5.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_t_005fdatagrid_005f0);
      // /webpage/com/jeecg/demo/logList.jsp(11,1) name = title type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_t_005fdgCol_005f5.setTitle("操作人名");
      // /webpage/com/jeecg/demo/logList.jsp(11,1) name = field type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_t_005fdgCol_005f5.setField("TSUser.realName");
      // /webpage/com/jeecg/demo/logList.jsp(11,1) name = width type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_t_005fdgCol_005f5.setWidth(new java.lang.Integer(200));
      int _jspx_eval_t_005fdgCol_005f5 = _jspx_th_t_005fdgCol_005f5.doStartTag();
      if (_jspx_th_t_005fdgCol_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ft_005fdgCol_0026_005fwidth_005ftitle_005ffield_005fnobody.reuse(_jspx_th_t_005fdgCol_005f5);
      _jspx_th_t_005fdgCol_005f5_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_t_005fdgCol_005f5, _jsp_getInstanceManager(), _jspx_th_t_005fdgCol_005f5_reused);
    }
    return false;
  }

  private boolean _jspx_meth_t_005fdgCol_005f6(javax.servlet.jsp.tagext.JspTag _jspx_th_t_005fdatagrid_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  t:dgCol
    org.jeecgframework.tag.core.easyui.DataGridColumnTag _jspx_th_t_005fdgCol_005f6 = (org.jeecgframework.tag.core.easyui.DataGridColumnTag) _005fjspx_005ftagPool_005ft_005fdgCol_0026_005fwidth_005ftitle_005ffield_005fnobody.get(org.jeecgframework.tag.core.easyui.DataGridColumnTag.class);
    boolean _jspx_th_t_005fdgCol_005f6_reused = false;
    try {
      _jspx_th_t_005fdgCol_005f6.setPageContext(_jspx_page_context);
      _jspx_th_t_005fdgCol_005f6.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_t_005fdatagrid_005f0);
      // /webpage/com/jeecg/demo/logList.jsp(12,1) name = title type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_t_005fdgCol_005f6.setTitle("浏览器");
      // /webpage/com/jeecg/demo/logList.jsp(12,1) name = field type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_t_005fdgCol_005f6.setField("broswer");
      // /webpage/com/jeecg/demo/logList.jsp(12,1) name = width type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_t_005fdgCol_005f6.setWidth(new java.lang.Integer(100));
      int _jspx_eval_t_005fdgCol_005f6 = _jspx_th_t_005fdgCol_005f6.doStartTag();
      if (_jspx_th_t_005fdgCol_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ft_005fdgCol_0026_005fwidth_005ftitle_005ffield_005fnobody.reuse(_jspx_th_t_005fdgCol_005f6);
      _jspx_th_t_005fdgCol_005f6_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_t_005fdgCol_005f6, _jsp_getInstanceManager(), _jspx_th_t_005fdgCol_005f6_reused);
    }
    return false;
  }

  private boolean _jspx_meth_t_005fdgCol_005f7(javax.servlet.jsp.tagext.JspTag _jspx_th_t_005fdatagrid_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  t:dgCol
    org.jeecgframework.tag.core.easyui.DataGridColumnTag _jspx_th_t_005fdgCol_005f7 = (org.jeecgframework.tag.core.easyui.DataGridColumnTag) _005fjspx_005ftagPool_005ft_005fdgCol_0026_005fwidth_005ftitle_005fqueryMode_005fquery_005fformatter_005ffield_005fnobody.get(org.jeecgframework.tag.core.easyui.DataGridColumnTag.class);
    boolean _jspx_th_t_005fdgCol_005f7_reused = false;
    try {
      _jspx_th_t_005fdgCol_005f7.setPageContext(_jspx_page_context);
      _jspx_th_t_005fdgCol_005f7.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_t_005fdatagrid_005f0);
      // /webpage/com/jeecg/demo/logList.jsp(13,1) name = title type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_t_005fdgCol_005f7.setTitle("operate.time");
      // /webpage/com/jeecg/demo/logList.jsp(13,1) name = field type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_t_005fdgCol_005f7.setField("operatetime");
      // /webpage/com/jeecg/demo/logList.jsp(13,1) name = query type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_t_005fdgCol_005f7.setQuery(true);
      // /webpage/com/jeecg/demo/logList.jsp(13,1) name = queryMode type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_t_005fdgCol_005f7.setQueryMode("group");
      // /webpage/com/jeecg/demo/logList.jsp(13,1) name = formatter type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_t_005fdgCol_005f7.setFormatter("yyyy-MM-dd hh:mm:ss");
      // /webpage/com/jeecg/demo/logList.jsp(13,1) name = width type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_t_005fdgCol_005f7.setWidth(new java.lang.Integer(200));
      int _jspx_eval_t_005fdgCol_005f7 = _jspx_th_t_005fdgCol_005f7.doStartTag();
      if (_jspx_th_t_005fdgCol_005f7.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ft_005fdgCol_0026_005fwidth_005ftitle_005fqueryMode_005fquery_005fformatter_005ffield_005fnobody.reuse(_jspx_th_t_005fdgCol_005f7);
      _jspx_th_t_005fdgCol_005f7_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_t_005fdgCol_005f7, _jsp_getInstanceManager(), _jspx_th_t_005fdgCol_005f7_reused);
    }
    return false;
  }

  private boolean _jspx_meth_t_005fdgToolBar_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_t_005fdatagrid_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  t:dgToolBar
    org.jeecgframework.tag.core.easyui.DataGridToolBarTag _jspx_th_t_005fdgToolBar_005f0 = (org.jeecgframework.tag.core.easyui.DataGridToolBarTag) _005fjspx_005ftagPool_005ft_005fdgToolBar_0026_005furl_005ftitle_005ficon_005ffunname_005fnobody.get(org.jeecgframework.tag.core.easyui.DataGridToolBarTag.class);
    boolean _jspx_th_t_005fdgToolBar_005f0_reused = false;
    try {
      _jspx_th_t_005fdgToolBar_005f0.setPageContext(_jspx_page_context);
      _jspx_th_t_005fdgToolBar_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_t_005fdatagrid_005f0);
      // /webpage/com/jeecg/demo/logList.jsp(15,2) name = title type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_t_005fdgToolBar_005f0.setTitle("数据报表");
      // /webpage/com/jeecg/demo/logList.jsp(15,2) name = icon type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_t_005fdgToolBar_005f0.setIcon("icon-search");
      // /webpage/com/jeecg/demo/logList.jsp(15,2) name = url type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_t_005fdgToolBar_005f0.setUrl("jeecgListDemoController.do?goOnlyData");
      // /webpage/com/jeecg/demo/logList.jsp(15,2) name = funname type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_t_005fdgToolBar_005f0.setFunname("goBaobiao");
      int _jspx_eval_t_005fdgToolBar_005f0 = _jspx_th_t_005fdgToolBar_005f0.doStartTag();
      if (_jspx_th_t_005fdgToolBar_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ft_005fdgToolBar_0026_005furl_005ftitle_005ficon_005ffunname_005fnobody.reuse(_jspx_th_t_005fdgToolBar_005f0);
      _jspx_th_t_005fdgToolBar_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_t_005fdgToolBar_005f0, _jsp_getInstanceManager(), _jspx_th_t_005fdgToolBar_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_t_005fdgToolBar_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_t_005fdatagrid_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  t:dgToolBar
    org.jeecgframework.tag.core.easyui.DataGridToolBarTag _jspx_th_t_005fdgToolBar_005f1 = (org.jeecgframework.tag.core.easyui.DataGridToolBarTag) _005fjspx_005ftagPool_005ft_005fdgToolBar_0026_005furl_005ftitle_005ficon_005ffunname_005fnobody.get(org.jeecgframework.tag.core.easyui.DataGridToolBarTag.class);
    boolean _jspx_th_t_005fdgToolBar_005f1_reused = false;
    try {
      _jspx_th_t_005fdgToolBar_005f1.setPageContext(_jspx_page_context);
      _jspx_th_t_005fdgToolBar_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_t_005fdatagrid_005f0);
      // /webpage/com/jeecg/demo/logList.jsp(16,2) name = title type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_t_005fdgToolBar_005f1.setTitle("图形报表");
      // /webpage/com/jeecg/demo/logList.jsp(16,2) name = icon type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_t_005fdgToolBar_005f1.setIcon("icon-search");
      // /webpage/com/jeecg/demo/logList.jsp(16,2) name = url type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_t_005fdgToolBar_005f1.setUrl("jeecgListDemoController.do?goChart");
      // /webpage/com/jeecg/demo/logList.jsp(16,2) name = funname type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_t_005fdgToolBar_005f1.setFunname("goBaobiao2");
      int _jspx_eval_t_005fdgToolBar_005f1 = _jspx_th_t_005fdgToolBar_005f1.doStartTag();
      if (_jspx_th_t_005fdgToolBar_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ft_005fdgToolBar_0026_005furl_005ftitle_005ficon_005ffunname_005fnobody.reuse(_jspx_th_t_005fdgToolBar_005f1);
      _jspx_th_t_005fdgToolBar_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_t_005fdgToolBar_005f1, _jsp_getInstanceManager(), _jspx_th_t_005fdgToolBar_005f1_reused);
    }
    return false;
  }
}
