/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.82
 * Generated at: 2018-07-29 14:57:09 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.webpage.com.jeecg.demo;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class taglist_005fminidao_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/tld/easyui.tld", Long.valueOf(1520613796042L));
    _jspx_dependants.put("/context/mytags.jsp", Long.valueOf(1520613796052L));
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ft_005fbase_0026_005ftype_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ft_005fdatagrid_0026_005ftitle_005fqueryMode_005fpagination_005fname_005fidField_005ffitColumns_005ffit_005fcheckbox_005factionUrl;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ft_005fdgCol_0026_005fwidth_005ftitle_005fqueryMode_005fhidden_005ffield_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ft_005fdgCol_0026_005fwidth_005ftitle_005fquery_005ffield_005fautocomplete_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ft_005fdgCol_0026_005fwidth_005ftitle_005fquery_005ffield_005fextend_005feditor_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ft_005fdgCol_0026_005fwidth_005ftitle_005fqueryMode_005fformatter_005ffield_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ft_005fdgCol_0026_005fwidth_005ftitle_005fqueryMode_005fquery_005ffield_005fdictionary_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ft_005fdgCol_0026_005fwidth_005ftitle_005fquery_005ffield_005fdictionary_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ft_005fdgCol_0026_005fwidth_005ftitle_005fqueryMode_005ffield_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ft_005fdgCol_0026_005fwidth_005ftitle_005fqueryMode_005fquery_005fformatter_005ffield_005feditor_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ft_005fdgCol_0026_005fwidth_005ftitle_005ffield_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ft_005fdgToolBar_0026_005furl_005ftitle_005ficon_005ffunname_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ft_005fbase_0026_005ftype_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ft_005fdatagrid_0026_005ftitle_005fqueryMode_005fpagination_005fname_005fidField_005ffitColumns_005ffit_005fcheckbox_005factionUrl = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ft_005fdgCol_0026_005fwidth_005ftitle_005fqueryMode_005fhidden_005ffield_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ft_005fdgCol_0026_005fwidth_005ftitle_005fquery_005ffield_005fautocomplete_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ft_005fdgCol_0026_005fwidth_005ftitle_005fquery_005ffield_005fextend_005feditor_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ft_005fdgCol_0026_005fwidth_005ftitle_005fqueryMode_005fformatter_005ffield_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ft_005fdgCol_0026_005fwidth_005ftitle_005fqueryMode_005fquery_005ffield_005fdictionary_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ft_005fdgCol_0026_005fwidth_005ftitle_005fquery_005ffield_005fdictionary_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ft_005fdgCol_0026_005fwidth_005ftitle_005fqueryMode_005ffield_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ft_005fdgCol_0026_005fwidth_005ftitle_005fqueryMode_005fquery_005fformatter_005ffield_005feditor_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ft_005fdgCol_0026_005fwidth_005ftitle_005ffield_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ft_005fdgToolBar_0026_005furl_005ftitle_005ficon_005ffunname_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005ft_005fbase_0026_005ftype_005fnobody.release();
    _005fjspx_005ftagPool_005ft_005fdatagrid_0026_005ftitle_005fqueryMode_005fpagination_005fname_005fidField_005ffitColumns_005ffit_005fcheckbox_005factionUrl.release();
    _005fjspx_005ftagPool_005ft_005fdgCol_0026_005fwidth_005ftitle_005fqueryMode_005fhidden_005ffield_005fnobody.release();
    _005fjspx_005ftagPool_005ft_005fdgCol_0026_005fwidth_005ftitle_005fquery_005ffield_005fautocomplete_005fnobody.release();
    _005fjspx_005ftagPool_005ft_005fdgCol_0026_005fwidth_005ftitle_005fquery_005ffield_005fextend_005feditor_005fnobody.release();
    _005fjspx_005ftagPool_005ft_005fdgCol_0026_005fwidth_005ftitle_005fqueryMode_005fformatter_005ffield_005fnobody.release();
    _005fjspx_005ftagPool_005ft_005fdgCol_0026_005fwidth_005ftitle_005fqueryMode_005fquery_005ffield_005fdictionary_005fnobody.release();
    _005fjspx_005ftagPool_005ft_005fdgCol_0026_005fwidth_005ftitle_005fquery_005ffield_005fdictionary_005fnobody.release();
    _005fjspx_005ftagPool_005ft_005fdgCol_0026_005fwidth_005ftitle_005fqueryMode_005ffield_005fnobody.release();
    _005fjspx_005ftagPool_005ft_005fdgCol_0026_005fwidth_005ftitle_005fqueryMode_005fquery_005fformatter_005ffield_005feditor_005fnobody.release();
    _005fjspx_005ftagPool_005ft_005fdgCol_0026_005fwidth_005ftitle_005ffield_005fnobody.release();
    _005fjspx_005ftagPool_005ft_005fdgToolBar_0026_005furl_005ftitle_005ficon_005ffunname_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
 
String path = request.getContextPath();
String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path;

      out.write('\n');
      //  c:set
      org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
      boolean _jspx_th_c_005fset_005f0_reused = false;
      try {
        _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
        _jspx_th_c_005fset_005f0.setParent(null);
        // /context/mytags.jsp(9,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_c_005fset_005f0.setVar("webRoot");
        // /context/mytags.jsp(9,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
        _jspx_th_c_005fset_005f0.setValue(basePath);
        int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
        if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
        _jspx_th_c_005fset_005f0_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
      }
      out.write('\n');
      if (_jspx_meth_t_005fbase_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("<div class=\"easyui-layout\" fit=\"true\">\n");
      out.write("  <div region=\"center\" style=\"padding:0px;border:0px\">\n");
      out.write("  ");
      if (_jspx_meth_t_005fdatagrid_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("  </div>\n");
      out.write(" </div>\n");
      out.write(" <!-- add-begin--Author:weict  Date:20170609 for：TASK #2087 【demo】springjdbc demo-------------------- -->\n");
      out.write(" <script type=\"text/javascript\">\n");
      out.write(" function toController(title,url,name){\n");
      out.write(" $.ajax({\n");
      out.write("\t\tasync : false,\n");
      out.write("\t\tcache : false,\n");
      out.write("\t\ttype : 'POST',\n");
      out.write("\t\turl : url,// 请求的action路径\n");
      out.write("\t\terror : function() {// 请求失败处理函数\n");
      out.write("\t\t},\n");
      out.write("\t\tsuccess : function(data) {\n");
      out.write("\t\t\tvar d = $.parseJSON(data);\n");
      out.write("\t\t\tif (d.success) {\n");
      out.write("\t\t\t\tvar msg = d.msg;\n");
      out.write("\t\t\t\ttip(msg);\n");
      out.write("\t\t\t\t$(\"#\"+name).datagrid('reload')\n");
      out.write("\t\t\t} else {\n");
      out.write("\t\t\t\ttip(d.msg);\n");
      out.write("\t\t\t}\n");
      out.write("\t\t}\n");
      out.write("\t});\n");
      out.write(" }\n");
      out.write(" </script>\n");
      out.write(" <!-- add-end--Author:weict  Date:20170609 for：TASK #2087 【demo】springjdbc demo---------------------- -->");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_t_005fbase_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  t:base
    org.jeecgframework.tag.core.easyui.BaseTag _jspx_th_t_005fbase_005f0 = (org.jeecgframework.tag.core.easyui.BaseTag) _005fjspx_005ftagPool_005ft_005fbase_0026_005ftype_005fnobody.get(org.jeecgframework.tag.core.easyui.BaseTag.class);
    boolean _jspx_th_t_005fbase_005f0_reused = false;
    try {
      _jspx_th_t_005fbase_005f0.setPageContext(_jspx_page_context);
      _jspx_th_t_005fbase_005f0.setParent(null);
      // /webpage/com/jeecg/demo/taglist_minidao.jsp(3,0) name = type type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_t_005fbase_005f0.setType("jquery,easyui,tools,DatePicker,autocomplete");
      int _jspx_eval_t_005fbase_005f0 = _jspx_th_t_005fbase_005f0.doStartTag();
      if (_jspx_th_t_005fbase_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ft_005fbase_0026_005ftype_005fnobody.reuse(_jspx_th_t_005fbase_005f0);
      _jspx_th_t_005fbase_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_t_005fbase_005f0, _jsp_getInstanceManager(), _jspx_th_t_005fbase_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_t_005fdatagrid_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  t:datagrid
    org.jeecgframework.tag.core.easyui.DataGridTag _jspx_th_t_005fdatagrid_005f0 = (org.jeecgframework.tag.core.easyui.DataGridTag) _005fjspx_005ftagPool_005ft_005fdatagrid_0026_005ftitle_005fqueryMode_005fpagination_005fname_005fidField_005ffitColumns_005ffit_005fcheckbox_005factionUrl.get(org.jeecgframework.tag.core.easyui.DataGridTag.class);
    boolean _jspx_th_t_005fdatagrid_005f0_reused = false;
    try {
      _jspx_th_t_005fdatagrid_005f0.setPageContext(_jspx_page_context);
      _jspx_th_t_005fdatagrid_005f0.setParent(null);
      // /webpage/com/jeecg/demo/taglist_minidao.jsp(6,2) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_t_005fdatagrid_005f0.setName("jeecgMinidaoList");
      // /webpage/com/jeecg/demo/taglist_minidao.jsp(6,2) name = checkbox type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_t_005fdatagrid_005f0.setCheckbox(true);
      // /webpage/com/jeecg/demo/taglist_minidao.jsp(6,2) name = pagination type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_t_005fdatagrid_005f0.setPagination(true);
      // /webpage/com/jeecg/demo/taglist_minidao.jsp(6,2) name = fitColumns type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_t_005fdatagrid_005f0.setFitColumns(false);
      // /webpage/com/jeecg/demo/taglist_minidao.jsp(6,2) name = title type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_t_005fdatagrid_005f0.setTitle("用户Demo列表，采用minidao查询数据");
      // /webpage/com/jeecg/demo/taglist_minidao.jsp(6,2) name = actionUrl type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_t_005fdatagrid_005f0.setActionUrl("jeecgListDemoController.do?minidaoDatagrid");
      // /webpage/com/jeecg/demo/taglist_minidao.jsp(6,2) name = idField type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_t_005fdatagrid_005f0.setIdField("id");
      // /webpage/com/jeecg/demo/taglist_minidao.jsp(6,2) name = fit type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_t_005fdatagrid_005f0.setFit(true);
      // /webpage/com/jeecg/demo/taglist_minidao.jsp(6,2) name = queryMode type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_t_005fdatagrid_005f0.setQueryMode("group");
      int _jspx_eval_t_005fdatagrid_005f0 = _jspx_th_t_005fdatagrid_005f0.doStartTag();
      if (_jspx_eval_t_005fdatagrid_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("    ");
          if (_jspx_meth_t_005fdgCol_005f0(_jspx_th_t_005fdatagrid_005f0, _jspx_page_context))
            return true;
          out.write("\n");
          out.write("    ");
          if (_jspx_meth_t_005fdgCol_005f1(_jspx_th_t_005fdatagrid_005f0, _jspx_page_context))
            return true;
          out.write("\n");
          out.write("    ");
          if (_jspx_meth_t_005fdgCol_005f2(_jspx_th_t_005fdatagrid_005f0, _jspx_page_context))
            return true;
          out.write("\n");
          out.write("    ");
          if (_jspx_meth_t_005fdgCol_005f3(_jspx_th_t_005fdatagrid_005f0, _jspx_page_context))
            return true;
          out.write("\n");
          out.write("    ");
          if (_jspx_meth_t_005fdgCol_005f4(_jspx_th_t_005fdatagrid_005f0, _jspx_page_context))
            return true;
          out.write("\n");
          out.write("    ");
          if (_jspx_meth_t_005fdgCol_005f5(_jspx_th_t_005fdatagrid_005f0, _jspx_page_context))
            return true;
          out.write("\n");
          out.write("    ");
          if (_jspx_meth_t_005fdgCol_005f6(_jspx_th_t_005fdatagrid_005f0, _jspx_page_context))
            return true;
          out.write("\n");
          out.write("    ");
          if (_jspx_meth_t_005fdgCol_005f7(_jspx_th_t_005fdatagrid_005f0, _jspx_page_context))
            return true;
          out.write("\n");
          out.write("    ");
          if (_jspx_meth_t_005fdgCol_005f8(_jspx_th_t_005fdatagrid_005f0, _jspx_page_context))
            return true;
          out.write("\n");
          out.write("    ");
          if (_jspx_meth_t_005fdgCol_005f9(_jspx_th_t_005fdatagrid_005f0, _jspx_page_context))
            return true;
          out.write("\n");
          out.write("    ");
          if (_jspx_meth_t_005fdgCol_005f10(_jspx_th_t_005fdatagrid_005f0, _jspx_page_context))
            return true;
          out.write("\n");
          out.write("    ");
          if (_jspx_meth_t_005fdgCol_005f11(_jspx_th_t_005fdatagrid_005f0, _jspx_page_context))
            return true;
          out.write("\n");
          out.write("    ");
          if (_jspx_meth_t_005fdgCol_005f12(_jspx_th_t_005fdatagrid_005f0, _jspx_page_context))
            return true;
          out.write("\n");
          out.write("    <!-- add-begin--Author:weict  Date:20170609 for：TASK #2087 【demo】springjdbc demo-------------------- -->\n");
          out.write("    ");
          if (_jspx_meth_t_005fdgToolBar_005f0(_jspx_th_t_005fdatagrid_005f0, _jspx_page_context))
            return true;
          out.write("\n");
          out.write("    ");
          if (_jspx_meth_t_005fdgToolBar_005f1(_jspx_th_t_005fdatagrid_005f0, _jspx_page_context))
            return true;
          out.write("\n");
          out.write("    <!-- add-end--Author:weict  Date:20170609 for：TASK #2087 【demo】springjdbc demo---------------------- -->\n");
          out.write("\n");
          out.write("       \n");
          out.write("  ");
          int evalDoAfterBody = _jspx_th_t_005fdatagrid_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_t_005fdatagrid_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ft_005fdatagrid_0026_005ftitle_005fqueryMode_005fpagination_005fname_005fidField_005ffitColumns_005ffit_005fcheckbox_005factionUrl.reuse(_jspx_th_t_005fdatagrid_005f0);
      _jspx_th_t_005fdatagrid_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_t_005fdatagrid_005f0, _jsp_getInstanceManager(), _jspx_th_t_005fdatagrid_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_t_005fdgCol_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_t_005fdatagrid_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  t:dgCol
    org.jeecgframework.tag.core.easyui.DataGridColumnTag _jspx_th_t_005fdgCol_005f0 = (org.jeecgframework.tag.core.easyui.DataGridColumnTag) _005fjspx_005ftagPool_005ft_005fdgCol_0026_005fwidth_005ftitle_005fqueryMode_005fhidden_005ffield_005fnobody.get(org.jeecgframework.tag.core.easyui.DataGridColumnTag.class);
    boolean _jspx_th_t_005fdgCol_005f0_reused = false;
    try {
      _jspx_th_t_005fdgCol_005f0.setPageContext(_jspx_page_context);
      _jspx_th_t_005fdgCol_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_t_005fdatagrid_005f0);
      // /webpage/com/jeecg/demo/taglist_minidao.jsp(7,4) name = title type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_t_005fdgCol_005f0.setTitle("id");
      // /webpage/com/jeecg/demo/taglist_minidao.jsp(7,4) name = field type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_t_005fdgCol_005f0.setField("id");
      // /webpage/com/jeecg/demo/taglist_minidao.jsp(7,4) name = hidden type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_t_005fdgCol_005f0.setHidden(true);
      // /webpage/com/jeecg/demo/taglist_minidao.jsp(7,4) name = queryMode type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_t_005fdgCol_005f0.setQueryMode("group");
      // /webpage/com/jeecg/demo/taglist_minidao.jsp(7,4) name = width type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_t_005fdgCol_005f0.setWidth(new java.lang.Integer(120));
      int _jspx_eval_t_005fdgCol_005f0 = _jspx_th_t_005fdgCol_005f0.doStartTag();
      if (_jspx_th_t_005fdgCol_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ft_005fdgCol_0026_005fwidth_005ftitle_005fqueryMode_005fhidden_005ffield_005fnobody.reuse(_jspx_th_t_005fdgCol_005f0);
      _jspx_th_t_005fdgCol_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_t_005fdgCol_005f0, _jsp_getInstanceManager(), _jspx_th_t_005fdgCol_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_t_005fdgCol_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_t_005fdatagrid_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  t:dgCol
    org.jeecgframework.tag.core.easyui.DataGridColumnTag _jspx_th_t_005fdgCol_005f1 = (org.jeecgframework.tag.core.easyui.DataGridColumnTag) _005fjspx_005ftagPool_005ft_005fdgCol_0026_005fwidth_005ftitle_005fquery_005ffield_005fautocomplete_005fnobody.get(org.jeecgframework.tag.core.easyui.DataGridColumnTag.class);
    boolean _jspx_th_t_005fdgCol_005f1_reused = false;
    try {
      _jspx_th_t_005fdgCol_005f1.setPageContext(_jspx_page_context);
      _jspx_th_t_005fdgCol_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_t_005fdatagrid_005f0);
      // /webpage/com/jeecg/demo/taglist_minidao.jsp(8,4) name = title type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_t_005fdgCol_005f1.setTitle("名称");
      // /webpage/com/jeecg/demo/taglist_minidao.jsp(8,4) name = field type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_t_005fdgCol_005f1.setField("name");
      // /webpage/com/jeecg/demo/taglist_minidao.jsp(8,4) name = query type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_t_005fdgCol_005f1.setQuery(true);
      // /webpage/com/jeecg/demo/taglist_minidao.jsp(8,4) name = autocomplete type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_t_005fdgCol_005f1.setAutocomplete(true);
      // /webpage/com/jeecg/demo/taglist_minidao.jsp(8,4) name = width type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_t_005fdgCol_005f1.setWidth(new java.lang.Integer(120));
      int _jspx_eval_t_005fdgCol_005f1 = _jspx_th_t_005fdgCol_005f1.doStartTag();
      if (_jspx_th_t_005fdgCol_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ft_005fdgCol_0026_005fwidth_005ftitle_005fquery_005ffield_005fautocomplete_005fnobody.reuse(_jspx_th_t_005fdgCol_005f1);
      _jspx_th_t_005fdgCol_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_t_005fdgCol_005f1, _jsp_getInstanceManager(), _jspx_th_t_005fdgCol_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_t_005fdgCol_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_t_005fdatagrid_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  t:dgCol
    org.jeecgframework.tag.core.easyui.DataGridColumnTag _jspx_th_t_005fdgCol_005f2 = (org.jeecgframework.tag.core.easyui.DataGridColumnTag) _005fjspx_005ftagPool_005ft_005fdgCol_0026_005fwidth_005ftitle_005fquery_005ffield_005fextend_005feditor_005fnobody.get(org.jeecgframework.tag.core.easyui.DataGridColumnTag.class);
    boolean _jspx_th_t_005fdgCol_005f2_reused = false;
    try {
      _jspx_th_t_005fdgCol_005f2.setPageContext(_jspx_page_context);
      _jspx_th_t_005fdgCol_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_t_005fdatagrid_005f0);
      // /webpage/com/jeecg/demo/taglist_minidao.jsp(9,4) name = title type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_t_005fdgCol_005f2.setTitle("年龄");
      // /webpage/com/jeecg/demo/taglist_minidao.jsp(9,4) name = extend type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_t_005fdgCol_005f2.setExtend("{style:'width:50px;color:red'}");
      // /webpage/com/jeecg/demo/taglist_minidao.jsp(9,4) name = editor type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_t_005fdgCol_005f2.setEditor("numberbox");
      // /webpage/com/jeecg/demo/taglist_minidao.jsp(9,4) name = field type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_t_005fdgCol_005f2.setField("age");
      // /webpage/com/jeecg/demo/taglist_minidao.jsp(9,4) name = query type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_t_005fdgCol_005f2.setQuery(true);
      // /webpage/com/jeecg/demo/taglist_minidao.jsp(9,4) name = width type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_t_005fdgCol_005f2.setWidth(new java.lang.Integer(120));
      int _jspx_eval_t_005fdgCol_005f2 = _jspx_th_t_005fdgCol_005f2.doStartTag();
      if (_jspx_th_t_005fdgCol_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ft_005fdgCol_0026_005fwidth_005ftitle_005fquery_005ffield_005fextend_005feditor_005fnobody.reuse(_jspx_th_t_005fdgCol_005f2);
      _jspx_th_t_005fdgCol_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_t_005fdgCol_005f2, _jsp_getInstanceManager(), _jspx_th_t_005fdgCol_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_t_005fdgCol_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_t_005fdatagrid_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  t:dgCol
    org.jeecgframework.tag.core.easyui.DataGridColumnTag _jspx_th_t_005fdgCol_005f3 = (org.jeecgframework.tag.core.easyui.DataGridColumnTag) _005fjspx_005ftagPool_005ft_005fdgCol_0026_005fwidth_005ftitle_005fqueryMode_005fformatter_005ffield_005fnobody.get(org.jeecgframework.tag.core.easyui.DataGridColumnTag.class);
    boolean _jspx_th_t_005fdgCol_005f3_reused = false;
    try {
      _jspx_th_t_005fdgCol_005f3.setPageContext(_jspx_page_context);
      _jspx_th_t_005fdgCol_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_t_005fdatagrid_005f0);
      // /webpage/com/jeecg/demo/taglist_minidao.jsp(10,4) name = title type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_t_005fdgCol_005f3.setTitle("生日");
      // /webpage/com/jeecg/demo/taglist_minidao.jsp(10,4) name = field type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_t_005fdgCol_005f3.setField("birthday");
      // /webpage/com/jeecg/demo/taglist_minidao.jsp(10,4) name = formatter type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_t_005fdgCol_005f3.setFormatter("yyyy-MM-dd");
      // /webpage/com/jeecg/demo/taglist_minidao.jsp(10,4) name = queryMode type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_t_005fdgCol_005f3.setQueryMode("group");
      // /webpage/com/jeecg/demo/taglist_minidao.jsp(10,4) name = width type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_t_005fdgCol_005f3.setWidth(new java.lang.Integer(120));
      int _jspx_eval_t_005fdgCol_005f3 = _jspx_th_t_005fdgCol_005f3.doStartTag();
      if (_jspx_th_t_005fdgCol_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ft_005fdgCol_0026_005fwidth_005ftitle_005fqueryMode_005fformatter_005ffield_005fnobody.reuse(_jspx_th_t_005fdgCol_005f3);
      _jspx_th_t_005fdgCol_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_t_005fdgCol_005f3, _jsp_getInstanceManager(), _jspx_th_t_005fdgCol_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_t_005fdgCol_005f4(javax.servlet.jsp.tagext.JspTag _jspx_th_t_005fdatagrid_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  t:dgCol
    org.jeecgframework.tag.core.easyui.DataGridColumnTag _jspx_th_t_005fdgCol_005f4 = (org.jeecgframework.tag.core.easyui.DataGridColumnTag) _005fjspx_005ftagPool_005ft_005fdgCol_0026_005fwidth_005ftitle_005fqueryMode_005fquery_005ffield_005fdictionary_005fnobody.get(org.jeecgframework.tag.core.easyui.DataGridColumnTag.class);
    boolean _jspx_th_t_005fdgCol_005f4_reused = false;
    try {
      _jspx_th_t_005fdgCol_005f4.setPageContext(_jspx_page_context);
      _jspx_th_t_005fdgCol_005f4.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_t_005fdatagrid_005f0);
      // /webpage/com/jeecg/demo/taglist_minidao.jsp(11,4) name = title type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_t_005fdgCol_005f4.setTitle("部门");
      // /webpage/com/jeecg/demo/taglist_minidao.jsp(11,4) name = field type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_t_005fdgCol_005f4.setField("depId");
      // /webpage/com/jeecg/demo/taglist_minidao.jsp(11,4) name = query type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_t_005fdgCol_005f4.setQuery(true);
      // /webpage/com/jeecg/demo/taglist_minidao.jsp(11,4) name = queryMode type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_t_005fdgCol_005f4.setQueryMode("single");
      // /webpage/com/jeecg/demo/taglist_minidao.jsp(11,4) name = dictionary type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_t_005fdgCol_005f4.setDictionary("t_s_depart,id,departname");
      // /webpage/com/jeecg/demo/taglist_minidao.jsp(11,4) name = width type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_t_005fdgCol_005f4.setWidth(new java.lang.Integer(120));
      int _jspx_eval_t_005fdgCol_005f4 = _jspx_th_t_005fdgCol_005f4.doStartTag();
      if (_jspx_th_t_005fdgCol_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ft_005fdgCol_0026_005fwidth_005ftitle_005fqueryMode_005fquery_005ffield_005fdictionary_005fnobody.reuse(_jspx_th_t_005fdgCol_005f4);
      _jspx_th_t_005fdgCol_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_t_005fdgCol_005f4, _jsp_getInstanceManager(), _jspx_th_t_005fdgCol_005f4_reused);
    }
    return false;
  }

  private boolean _jspx_meth_t_005fdgCol_005f5(javax.servlet.jsp.tagext.JspTag _jspx_th_t_005fdatagrid_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  t:dgCol
    org.jeecgframework.tag.core.easyui.DataGridColumnTag _jspx_th_t_005fdgCol_005f5 = (org.jeecgframework.tag.core.easyui.DataGridColumnTag) _005fjspx_005ftagPool_005ft_005fdgCol_0026_005fwidth_005ftitle_005fquery_005ffield_005fdictionary_005fnobody.get(org.jeecgframework.tag.core.easyui.DataGridColumnTag.class);
    boolean _jspx_th_t_005fdgCol_005f5_reused = false;
    try {
      _jspx_th_t_005fdgCol_005f5.setPageContext(_jspx_page_context);
      _jspx_th_t_005fdgCol_005f5.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_t_005fdatagrid_005f0);
      // /webpage/com/jeecg/demo/taglist_minidao.jsp(12,4) name = title type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_t_005fdgCol_005f5.setTitle("性别");
      // /webpage/com/jeecg/demo/taglist_minidao.jsp(12,4) name = field type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_t_005fdgCol_005f5.setField("sex");
      // /webpage/com/jeecg/demo/taglist_minidao.jsp(12,4) name = query type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_t_005fdgCol_005f5.setQuery(true);
      // /webpage/com/jeecg/demo/taglist_minidao.jsp(12,4) name = dictionary type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_t_005fdgCol_005f5.setDictionary("sex");
      // /webpage/com/jeecg/demo/taglist_minidao.jsp(12,4) name = width type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_t_005fdgCol_005f5.setWidth(new java.lang.Integer(120));
      int _jspx_eval_t_005fdgCol_005f5 = _jspx_th_t_005fdgCol_005f5.doStartTag();
      if (_jspx_th_t_005fdgCol_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ft_005fdgCol_0026_005fwidth_005ftitle_005fquery_005ffield_005fdictionary_005fnobody.reuse(_jspx_th_t_005fdgCol_005f5);
      _jspx_th_t_005fdgCol_005f5_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_t_005fdgCol_005f5, _jsp_getInstanceManager(), _jspx_th_t_005fdgCol_005f5_reused);
    }
    return false;
  }

  private boolean _jspx_meth_t_005fdgCol_005f6(javax.servlet.jsp.tagext.JspTag _jspx_th_t_005fdatagrid_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  t:dgCol
    org.jeecgframework.tag.core.easyui.DataGridColumnTag _jspx_th_t_005fdgCol_005f6 = (org.jeecgframework.tag.core.easyui.DataGridColumnTag) _005fjspx_005ftagPool_005ft_005fdgCol_0026_005fwidth_005ftitle_005fqueryMode_005ffield_005fnobody.get(org.jeecgframework.tag.core.easyui.DataGridColumnTag.class);
    boolean _jspx_th_t_005fdgCol_005f6_reused = false;
    try {
      _jspx_th_t_005fdgCol_005f6.setPageContext(_jspx_page_context);
      _jspx_th_t_005fdgCol_005f6.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_t_005fdatagrid_005f0);
      // /webpage/com/jeecg/demo/taglist_minidao.jsp(13,4) name = title type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_t_005fdgCol_005f6.setTitle("电话");
      // /webpage/com/jeecg/demo/taglist_minidao.jsp(13,4) name = field type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_t_005fdgCol_005f6.setField("phone");
      // /webpage/com/jeecg/demo/taglist_minidao.jsp(13,4) name = queryMode type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_t_005fdgCol_005f6.setQueryMode("group");
      // /webpage/com/jeecg/demo/taglist_minidao.jsp(13,4) name = width type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_t_005fdgCol_005f6.setWidth(new java.lang.Integer(120));
      int _jspx_eval_t_005fdgCol_005f6 = _jspx_th_t_005fdgCol_005f6.doStartTag();
      if (_jspx_th_t_005fdgCol_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ft_005fdgCol_0026_005fwidth_005ftitle_005fqueryMode_005ffield_005fnobody.reuse(_jspx_th_t_005fdgCol_005f6);
      _jspx_th_t_005fdgCol_005f6_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_t_005fdgCol_005f6, _jsp_getInstanceManager(), _jspx_th_t_005fdgCol_005f6_reused);
    }
    return false;
  }

  private boolean _jspx_meth_t_005fdgCol_005f7(javax.servlet.jsp.tagext.JspTag _jspx_th_t_005fdatagrid_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  t:dgCol
    org.jeecgframework.tag.core.easyui.DataGridColumnTag _jspx_th_t_005fdgCol_005f7 = (org.jeecgframework.tag.core.easyui.DataGridColumnTag) _005fjspx_005ftagPool_005ft_005fdgCol_0026_005fwidth_005ftitle_005fqueryMode_005ffield_005fnobody.get(org.jeecgframework.tag.core.easyui.DataGridColumnTag.class);
    boolean _jspx_th_t_005fdgCol_005f7_reused = false;
    try {
      _jspx_th_t_005fdgCol_005f7.setPageContext(_jspx_page_context);
      _jspx_th_t_005fdgCol_005f7.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_t_005fdatagrid_005f0);
      // /webpage/com/jeecg/demo/taglist_minidao.jsp(14,4) name = title type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_t_005fdgCol_005f7.setTitle("工资");
      // /webpage/com/jeecg/demo/taglist_minidao.jsp(14,4) name = field type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_t_005fdgCol_005f7.setField("salary");
      // /webpage/com/jeecg/demo/taglist_minidao.jsp(14,4) name = queryMode type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_t_005fdgCol_005f7.setQueryMode("group");
      // /webpage/com/jeecg/demo/taglist_minidao.jsp(14,4) name = width type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_t_005fdgCol_005f7.setWidth(new java.lang.Integer(120));
      int _jspx_eval_t_005fdgCol_005f7 = _jspx_th_t_005fdgCol_005f7.doStartTag();
      if (_jspx_th_t_005fdgCol_005f7.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ft_005fdgCol_0026_005fwidth_005ftitle_005fqueryMode_005ffield_005fnobody.reuse(_jspx_th_t_005fdgCol_005f7);
      _jspx_th_t_005fdgCol_005f7_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_t_005fdgCol_005f7, _jsp_getInstanceManager(), _jspx_th_t_005fdgCol_005f7_reused);
    }
    return false;
  }

  private boolean _jspx_meth_t_005fdgCol_005f8(javax.servlet.jsp.tagext.JspTag _jspx_th_t_005fdatagrid_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  t:dgCol
    org.jeecgframework.tag.core.easyui.DataGridColumnTag _jspx_th_t_005fdgCol_005f8 = (org.jeecgframework.tag.core.easyui.DataGridColumnTag) _005fjspx_005ftagPool_005ft_005fdgCol_0026_005fwidth_005ftitle_005fqueryMode_005fquery_005fformatter_005ffield_005feditor_005fnobody.get(org.jeecgframework.tag.core.easyui.DataGridColumnTag.class);
    boolean _jspx_th_t_005fdgCol_005f8_reused = false;
    try {
      _jspx_th_t_005fdgCol_005f8.setPageContext(_jspx_page_context);
      _jspx_th_t_005fdgCol_005f8.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_t_005fdatagrid_005f0);
      // /webpage/com/jeecg/demo/taglist_minidao.jsp(15,4) name = title type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_t_005fdgCol_005f8.setTitle("创建日期");
      // /webpage/com/jeecg/demo/taglist_minidao.jsp(15,4) name = field type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_t_005fdgCol_005f8.setField("createDate");
      // /webpage/com/jeecg/demo/taglist_minidao.jsp(15,4) name = formatter type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_t_005fdgCol_005f8.setFormatter("yyyy-MM-dd");
      // /webpage/com/jeecg/demo/taglist_minidao.jsp(15,4) name = query type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_t_005fdgCol_005f8.setQuery(false);
      // /webpage/com/jeecg/demo/taglist_minidao.jsp(15,4) name = queryMode type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_t_005fdgCol_005f8.setQueryMode("group");
      // /webpage/com/jeecg/demo/taglist_minidao.jsp(15,4) name = editor type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_t_005fdgCol_005f8.setEditor("datebox");
      // /webpage/com/jeecg/demo/taglist_minidao.jsp(15,4) name = width type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_t_005fdgCol_005f8.setWidth(new java.lang.Integer(120));
      int _jspx_eval_t_005fdgCol_005f8 = _jspx_th_t_005fdgCol_005f8.doStartTag();
      if (_jspx_th_t_005fdgCol_005f8.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ft_005fdgCol_0026_005fwidth_005ftitle_005fqueryMode_005fquery_005fformatter_005ffield_005feditor_005fnobody.reuse(_jspx_th_t_005fdgCol_005f8);
      _jspx_th_t_005fdgCol_005f8_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_t_005fdgCol_005f8, _jsp_getInstanceManager(), _jspx_th_t_005fdgCol_005f8_reused);
    }
    return false;
  }

  private boolean _jspx_meth_t_005fdgCol_005f9(javax.servlet.jsp.tagext.JspTag _jspx_th_t_005fdatagrid_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  t:dgCol
    org.jeecgframework.tag.core.easyui.DataGridColumnTag _jspx_th_t_005fdgCol_005f9 = (org.jeecgframework.tag.core.easyui.DataGridColumnTag) _005fjspx_005ftagPool_005ft_005fdgCol_0026_005fwidth_005ftitle_005ffield_005fnobody.get(org.jeecgframework.tag.core.easyui.DataGridColumnTag.class);
    boolean _jspx_th_t_005fdgCol_005f9_reused = false;
    try {
      _jspx_th_t_005fdgCol_005f9.setPageContext(_jspx_page_context);
      _jspx_th_t_005fdgCol_005f9.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_t_005fdatagrid_005f0);
      // /webpage/com/jeecg/demo/taglist_minidao.jsp(16,4) name = title type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_t_005fdgCol_005f9.setTitle("创建人");
      // /webpage/com/jeecg/demo/taglist_minidao.jsp(16,4) name = field type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_t_005fdgCol_005f9.setField("createBy");
      // /webpage/com/jeecg/demo/taglist_minidao.jsp(16,4) name = width type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_t_005fdgCol_005f9.setWidth(new java.lang.Integer(120));
      int _jspx_eval_t_005fdgCol_005f9 = _jspx_th_t_005fdgCol_005f9.doStartTag();
      if (_jspx_th_t_005fdgCol_005f9.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ft_005fdgCol_0026_005fwidth_005ftitle_005ffield_005fnobody.reuse(_jspx_th_t_005fdgCol_005f9);
      _jspx_th_t_005fdgCol_005f9_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_t_005fdgCol_005f9, _jsp_getInstanceManager(), _jspx_th_t_005fdgCol_005f9_reused);
    }
    return false;
  }

  private boolean _jspx_meth_t_005fdgCol_005f10(javax.servlet.jsp.tagext.JspTag _jspx_th_t_005fdatagrid_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  t:dgCol
    org.jeecgframework.tag.core.easyui.DataGridColumnTag _jspx_th_t_005fdgCol_005f10 = (org.jeecgframework.tag.core.easyui.DataGridColumnTag) _005fjspx_005ftagPool_005ft_005fdgCol_0026_005fwidth_005ftitle_005fqueryMode_005fhidden_005ffield_005fnobody.get(org.jeecgframework.tag.core.easyui.DataGridColumnTag.class);
    boolean _jspx_th_t_005fdgCol_005f10_reused = false;
    try {
      _jspx_th_t_005fdgCol_005f10.setPageContext(_jspx_page_context);
      _jspx_th_t_005fdgCol_005f10.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_t_005fdatagrid_005f0);
      // /webpage/com/jeecg/demo/taglist_minidao.jsp(17,4) name = title type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_t_005fdgCol_005f10.setTitle("邮箱");
      // /webpage/com/jeecg/demo/taglist_minidao.jsp(17,4) name = field type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_t_005fdgCol_005f10.setField("email");
      // /webpage/com/jeecg/demo/taglist_minidao.jsp(17,4) name = hidden type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_t_005fdgCol_005f10.setHidden(true);
      // /webpage/com/jeecg/demo/taglist_minidao.jsp(17,4) name = queryMode type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_t_005fdgCol_005f10.setQueryMode("group");
      // /webpage/com/jeecg/demo/taglist_minidao.jsp(17,4) name = width type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_t_005fdgCol_005f10.setWidth(new java.lang.Integer(120));
      int _jspx_eval_t_005fdgCol_005f10 = _jspx_th_t_005fdgCol_005f10.doStartTag();
      if (_jspx_th_t_005fdgCol_005f10.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ft_005fdgCol_0026_005fwidth_005ftitle_005fqueryMode_005fhidden_005ffield_005fnobody.reuse(_jspx_th_t_005fdgCol_005f10);
      _jspx_th_t_005fdgCol_005f10_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_t_005fdgCol_005f10, _jsp_getInstanceManager(), _jspx_th_t_005fdgCol_005f10_reused);
    }
    return false;
  }

  private boolean _jspx_meth_t_005fdgCol_005f11(javax.servlet.jsp.tagext.JspTag _jspx_th_t_005fdatagrid_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  t:dgCol
    org.jeecgframework.tag.core.easyui.DataGridColumnTag _jspx_th_t_005fdgCol_005f11 = (org.jeecgframework.tag.core.easyui.DataGridColumnTag) _005fjspx_005ftagPool_005ft_005fdgCol_0026_005fwidth_005ftitle_005fquery_005ffield_005fdictionary_005fnobody.get(org.jeecgframework.tag.core.easyui.DataGridColumnTag.class);
    boolean _jspx_th_t_005fdgCol_005f11_reused = false;
    try {
      _jspx_th_t_005fdgCol_005f11.setPageContext(_jspx_page_context);
      _jspx_th_t_005fdgCol_005f11.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_t_005fdatagrid_005f0);
      // /webpage/com/jeecg/demo/taglist_minidao.jsp(18,4) name = title type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_t_005fdgCol_005f11.setTitle("入职状态");
      // /webpage/com/jeecg/demo/taglist_minidao.jsp(18,4) name = field type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_t_005fdgCol_005f11.setField("status");
      // /webpage/com/jeecg/demo/taglist_minidao.jsp(18,4) name = query type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_t_005fdgCol_005f11.setQuery(true);
      // /webpage/com/jeecg/demo/taglist_minidao.jsp(18,4) name = dictionary type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_t_005fdgCol_005f11.setDictionary("sf_yn");
      // /webpage/com/jeecg/demo/taglist_minidao.jsp(18,4) name = width type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_t_005fdgCol_005f11.setWidth(new java.lang.Integer(120));
      int _jspx_eval_t_005fdgCol_005f11 = _jspx_th_t_005fdgCol_005f11.doStartTag();
      if (_jspx_th_t_005fdgCol_005f11.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ft_005fdgCol_0026_005fwidth_005ftitle_005fquery_005ffield_005fdictionary_005fnobody.reuse(_jspx_th_t_005fdgCol_005f11);
      _jspx_th_t_005fdgCol_005f11_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_t_005fdgCol_005f11, _jsp_getInstanceManager(), _jspx_th_t_005fdgCol_005f11_reused);
    }
    return false;
  }

  private boolean _jspx_meth_t_005fdgCol_005f12(javax.servlet.jsp.tagext.JspTag _jspx_th_t_005fdatagrid_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  t:dgCol
    org.jeecgframework.tag.core.easyui.DataGridColumnTag _jspx_th_t_005fdgCol_005f12 = (org.jeecgframework.tag.core.easyui.DataGridColumnTag) _005fjspx_005ftagPool_005ft_005fdgCol_0026_005fwidth_005ftitle_005fqueryMode_005fhidden_005ffield_005fnobody.get(org.jeecgframework.tag.core.easyui.DataGridColumnTag.class);
    boolean _jspx_th_t_005fdgCol_005f12_reused = false;
    try {
      _jspx_th_t_005fdgCol_005f12.setPageContext(_jspx_page_context);
      _jspx_th_t_005fdgCol_005f12.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_t_005fdatagrid_005f0);
      // /webpage/com/jeecg/demo/taglist_minidao.jsp(19,4) name = title type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_t_005fdgCol_005f12.setTitle("个人介绍");
      // /webpage/com/jeecg/demo/taglist_minidao.jsp(19,4) name = field type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_t_005fdgCol_005f12.setField("content");
      // /webpage/com/jeecg/demo/taglist_minidao.jsp(19,4) name = hidden type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_t_005fdgCol_005f12.setHidden(true);
      // /webpage/com/jeecg/demo/taglist_minidao.jsp(19,4) name = queryMode type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_t_005fdgCol_005f12.setQueryMode("group");
      // /webpage/com/jeecg/demo/taglist_minidao.jsp(19,4) name = width type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_t_005fdgCol_005f12.setWidth(new java.lang.Integer(500));
      int _jspx_eval_t_005fdgCol_005f12 = _jspx_th_t_005fdgCol_005f12.doStartTag();
      if (_jspx_th_t_005fdgCol_005f12.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ft_005fdgCol_0026_005fwidth_005ftitle_005fqueryMode_005fhidden_005ffield_005fnobody.reuse(_jspx_th_t_005fdgCol_005f12);
      _jspx_th_t_005fdgCol_005f12_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_t_005fdgCol_005f12, _jsp_getInstanceManager(), _jspx_th_t_005fdgCol_005f12_reused);
    }
    return false;
  }

  private boolean _jspx_meth_t_005fdgToolBar_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_t_005fdatagrid_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  t:dgToolBar
    org.jeecgframework.tag.core.easyui.DataGridToolBarTag _jspx_th_t_005fdgToolBar_005f0 = (org.jeecgframework.tag.core.easyui.DataGridToolBarTag) _005fjspx_005ftagPool_005ft_005fdgToolBar_0026_005furl_005ftitle_005ficon_005ffunname_005fnobody.get(org.jeecgframework.tag.core.easyui.DataGridToolBarTag.class);
    boolean _jspx_th_t_005fdgToolBar_005f0_reused = false;
    try {
      _jspx_th_t_005fdgToolBar_005f0.setPageContext(_jspx_page_context);
      _jspx_th_t_005fdgToolBar_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_t_005fdatagrid_005f0);
      // /webpage/com/jeecg/demo/taglist_minidao.jsp(21,4) name = title type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_t_005fdgToolBar_005f0.setTitle("批量插入用户DEMO");
      // /webpage/com/jeecg/demo/taglist_minidao.jsp(21,4) name = icon type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_t_005fdgToolBar_005f0.setIcon("icon-add");
      // /webpage/com/jeecg/demo/taglist_minidao.jsp(21,4) name = url type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_t_005fdgToolBar_005f0.setUrl("jeecgListDemoController.do?jdbcBatchSave");
      // /webpage/com/jeecg/demo/taglist_minidao.jsp(21,4) name = funname type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_t_005fdgToolBar_005f0.setFunname("toController");
      int _jspx_eval_t_005fdgToolBar_005f0 = _jspx_th_t_005fdgToolBar_005f0.doStartTag();
      if (_jspx_th_t_005fdgToolBar_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ft_005fdgToolBar_0026_005furl_005ftitle_005ficon_005ffunname_005fnobody.reuse(_jspx_th_t_005fdgToolBar_005f0);
      _jspx_th_t_005fdgToolBar_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_t_005fdgToolBar_005f0, _jsp_getInstanceManager(), _jspx_th_t_005fdgToolBar_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_t_005fdgToolBar_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_t_005fdatagrid_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  t:dgToolBar
    org.jeecgframework.tag.core.easyui.DataGridToolBarTag _jspx_th_t_005fdgToolBar_005f1 = (org.jeecgframework.tag.core.easyui.DataGridToolBarTag) _005fjspx_005ftagPool_005ft_005fdgToolBar_0026_005furl_005ftitle_005ficon_005ffunname_005fnobody.get(org.jeecgframework.tag.core.easyui.DataGridToolBarTag.class);
    boolean _jspx_th_t_005fdgToolBar_005f1_reused = false;
    try {
      _jspx_th_t_005fdgToolBar_005f1.setPageContext(_jspx_page_context);
      _jspx_th_t_005fdgToolBar_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_t_005fdatagrid_005f0);
      // /webpage/com/jeecg/demo/taglist_minidao.jsp(22,4) name = title type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_t_005fdgToolBar_005f1.setTitle("调用存储批量删除用户DEMO");
      // /webpage/com/jeecg/demo/taglist_minidao.jsp(22,4) name = icon type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_t_005fdgToolBar_005f1.setIcon("icon-add");
      // /webpage/com/jeecg/demo/taglist_minidao.jsp(22,4) name = url type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_t_005fdgToolBar_005f1.setUrl("jeecgListDemoController.do?jdbcProcedure");
      // /webpage/com/jeecg/demo/taglist_minidao.jsp(22,4) name = funname type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_t_005fdgToolBar_005f1.setFunname("toController");
      int _jspx_eval_t_005fdgToolBar_005f1 = _jspx_th_t_005fdgToolBar_005f1.doStartTag();
      if (_jspx_th_t_005fdgToolBar_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ft_005fdgToolBar_0026_005furl_005ftitle_005ficon_005ffunname_005fnobody.reuse(_jspx_th_t_005fdgToolBar_005f1);
      _jspx_th_t_005fdgToolBar_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_t_005fdgToolBar_005f1, _jsp_getInstanceManager(), _jspx_th_t_005fdgToolBar_005f1_reused);
    }
    return false;
  }
}
