package com.haihoo.ws.cxf.soap12.hiWS;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.16
 * 2018-07-17T21:08:23.301+08:00
 * Generated source version: 3.0.16
 * 
 */
@WebService(targetNamespace = "http://soap12.server.cxf.ws.haihoo.com/", name = "HiServer")
@XmlSeeAlso({ObjectFactory.class})
public interface HiServer {

    @WebMethod
    @RequestWrapper(localName = "sysHi", targetNamespace = "http://soap12.server.cxf.ws.haihoo.com/", className = "com.haihoo.ws.cxf.soap12.hiWS.SysHi")
    @ResponseWrapper(localName = "sysHiResponse", targetNamespace = "http://soap12.server.cxf.ws.haihoo.com/", className = "com.haihoo.ws.cxf.soap12.hiWS.SysHiResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String sysHi(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
