/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.82
 * Generated at: 2018-07-29 14:54:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.webpage.system.notice;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class tSNotice_002dadd_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/tld/easyui.tld", Long.valueOf(1520613796042L));
    _jspx_dependants.put("/context/mytags.jsp", Long.valueOf(1520613796052L));
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ft_005fbase_0026_005ftype_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ft_005fformvalid_0026_005fusePlugin_005ftiptype_005flayout_005fformid_005fdialog_005fbeforeSubmit_005faction;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ft_005fchoose_0026_005furl_005ftitle_005ftextname_005fname_005fisclear_005fisInit_005ficon_005fhiddenid_005fhiddenName_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ft_005fbase_0026_005ftype_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ft_005fformvalid_0026_005fusePlugin_005ftiptype_005flayout_005fformid_005fdialog_005fbeforeSubmit_005faction = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ft_005fchoose_0026_005furl_005ftitle_005ftextname_005fname_005fisclear_005fisInit_005ficon_005fhiddenid_005fhiddenName_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005ft_005fbase_0026_005ftype_005fnobody.release();
    _005fjspx_005ftagPool_005ft_005fformvalid_0026_005fusePlugin_005ftiptype_005flayout_005fformid_005fdialog_005fbeforeSubmit_005faction.release();
    _005fjspx_005ftagPool_005ft_005fchoose_0026_005furl_005ftitle_005ftextname_005fname_005fisclear_005fisInit_005ficon_005fhiddenid_005fhiddenName_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
 
String path = request.getContextPath();
String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path;

      out.write('\n');
      //  c:set
      org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
      boolean _jspx_th_c_005fset_005f0_reused = false;
      try {
        _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
        _jspx_th_c_005fset_005f0.setParent(null);
        // /context/mytags.jsp(9,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_c_005fset_005f0.setVar("webRoot");
        // /context/mytags.jsp(9,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
        _jspx_th_c_005fset_005f0.setValue(basePath);
        int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
        if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
        _jspx_th_c_005fset_005f0_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
      }
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write(" <head>\n");
      out.write("  <title>common.notice</title>\n");
      out.write("  ");
      if (_jspx_meth_t_005fbase_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("  <script type=\"text/javascript\" charset=\"utf-8\" src=\"plug-in/ueditor/ueditor.config.js\"></script>\n");
      out.write("  <script type=\"text/javascript\" charset=\"utf-8\" src=\"plug-in/ueditor/ueditor.all.js\"> </script>\n");
      out.write("  <script type=\"text/javascript\">\n");
      out.write("  //编写自定义JS代码\n");
      out.write("  function setContent(){\n");
      out.write("\t    if(editor.queryCommandState( 'source' ))\n");
      out.write("\t    \teditor.execCommand('source');//切换到编辑模式才提交，否则有bug\n");
      out.write("\t            \n");
      out.write("\t    if(editor.hasContents()){\n");
      out.write("\t    \teditor.sync();\n");
      out.write("\t\t    $(\"#noticeContent\").val(editor.getContent());\n");
      out.write("\t\t}\n");
      out.write("\t}\n");
      out.write("  function dataytpeSelect(name) {\n");
      out.write("      $(\"#roleName\").removeAttr('datatype');\n");
      out.write("      $(\"#roleName_span\").hide()\n");
      out.write("      $(\"#userName\").removeAttr('datatype');\n");
      out.write("      $(\"#userName_span\").hide()\n");
      out.write("      if (name){\n");
      out.write("          $(\"#\"+name).attr('datatype','*');\n");
      out.write("          $(\"#\"+name+\"_span\").show()\n");
      out.write("      }\n");
      out.write("  }\n");
      out.write("\n");
      out.write("  </script>\n");
      out.write(" </head>\n");
      out.write(" <body>\n");
      out.write("  ");
      if (_jspx_meth_t_005fformvalid_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write(" </body>\n");
      out.write("\t\t");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_t_005fbase_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  t:base
    org.jeecgframework.tag.core.easyui.BaseTag _jspx_th_t_005fbase_005f0 = (org.jeecgframework.tag.core.easyui.BaseTag) _005fjspx_005ftagPool_005ft_005fbase_0026_005ftype_005fnobody.get(org.jeecgframework.tag.core.easyui.BaseTag.class);
    boolean _jspx_th_t_005fbase_005f0_reused = false;
    try {
      _jspx_th_t_005fbase_005f0.setPageContext(_jspx_page_context);
      _jspx_th_t_005fbase_005f0.setParent(null);
      // /webpage/system/notice/tSNotice-add.jsp(7,2) name = type type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_t_005fbase_005f0.setType("jquery,easyui,tools,DatePicker");
      int _jspx_eval_t_005fbase_005f0 = _jspx_th_t_005fbase_005f0.doStartTag();
      if (_jspx_th_t_005fbase_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ft_005fbase_0026_005ftype_005fnobody.reuse(_jspx_th_t_005fbase_005f0);
      _jspx_th_t_005fbase_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_t_005fbase_005f0, _jsp_getInstanceManager(), _jspx_th_t_005fbase_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_t_005fformvalid_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  t:formvalid
    org.jeecgframework.tag.core.easyui.FormValidationTag _jspx_th_t_005fformvalid_005f0 = (org.jeecgframework.tag.core.easyui.FormValidationTag) _005fjspx_005ftagPool_005ft_005fformvalid_0026_005fusePlugin_005ftiptype_005flayout_005fformid_005fdialog_005fbeforeSubmit_005faction.get(org.jeecgframework.tag.core.easyui.FormValidationTag.class);
    boolean _jspx_th_t_005fformvalid_005f0_reused = false;
    try {
      _jspx_th_t_005fformvalid_005f0.setPageContext(_jspx_page_context);
      _jspx_th_t_005fformvalid_005f0.setParent(null);
      // /webpage/system/notice/tSNotice-add.jsp(35,2) name = formid type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_t_005fformvalid_005f0.setFormid("formobj");
      // /webpage/system/notice/tSNotice-add.jsp(35,2) name = dialog type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_t_005fformvalid_005f0.setDialog(true);
      // /webpage/system/notice/tSNotice-add.jsp(35,2) name = usePlugin type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_t_005fformvalid_005f0.setUsePlugin("password");
      // /webpage/system/notice/tSNotice-add.jsp(35,2) name = layout type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_t_005fformvalid_005f0.setLayout("table");
      // /webpage/system/notice/tSNotice-add.jsp(35,2) name = action type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_t_005fformvalid_005f0.setAction("noticeController.do?doAdd");
      // /webpage/system/notice/tSNotice-add.jsp(35,2) name = tiptype type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_t_005fformvalid_005f0.setTiptype("1");
      // /webpage/system/notice/tSNotice-add.jsp(35,2) name = beforeSubmit type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_t_005fformvalid_005f0.setBeforeSubmit("setContent()");
      int _jspx_eval_t_005fformvalid_005f0 = _jspx_th_t_005fformvalid_005f0.doStartTag();
      if (_jspx_eval_t_005fformvalid_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("\t\t\t\t\t<input id=\"id\" name=\"id\" type=\"hidden\" value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${tSNoticePage.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("\">\n");
          out.write("\t\t<table style=\"width:100%\" cellpadding=\"0\" cellspacing=\"1\" class=\"formtable\">\n");
          out.write("\t\t\t\t<tr>\n");
          out.write("\t\t\t\t\t<td align=\"right\">\n");
          out.write("\t\t\t\t\t\t<label class=\"Validform_label\">\n");
          out.write("\t\t\t\t\t\t\t标题:\n");
          out.write("\t\t\t\t\t\t</label>\n");
          out.write("\t\t\t\t\t</td>\n");
          out.write("\t\t\t\t\t<td class=\"value\">\n");
          out.write("\t\t\t\t\t     \t <input id=\"noticeTitle\" name=\"noticeTitle\" type=\"text\" style=\"width:95%\" class=\"inputxt\"  >\n");
          out.write("\t\t\t\t\t\t\t<span class=\"Validform_checktip\"></span>\n");
          out.write("\t\t\t\t\t\t\t<label class=\"Validform_label\" style=\"display: none;\">通知标题</label>\n");
          out.write("\t\t\t\t\t\t</td>\n");
          out.write("\t\t\t\t</tr>\n");
          out.write("\t\t\t\t<tr>\n");
          out.write("\t\t\t\t\t<td align=\"right\">\n");
          out.write("\t\t\t\t\t\t<label class=\"Validform_label\">\n");
          out.write("\t\t\t\t\t\t\t内容:\n");
          out.write("\t\t\t\t\t\t</label>\n");
          out.write("\t\t\t\t\t</td>\n");
          out.write("\t\t\t\t\t<td class=\"value\">\n");
          out.write("\t\t\t\t\t\t  \t <input id=\"noticeContent\" name=\"noticeContent\" type=\"hidden\">\n");
          out.write("\t\t\t\t\t\t  \t <script id=\"content\" type=\"text/plain\" style=\"width:700px;\" ></script>\n");
          out.write("\t\t\t\t\t\t  \t <script type=\"text/javascript\">\n");
          out.write("\t\t\t\t\t\t        \tvar editor = UE.getEditor('content',{\n");
          out.write("\t\t\t\t\t\t        \t    toolleipi:true,//是否显示，设计器的 toolbars\n");
          out.write("\t\t\t\t\t\t        \t    textarea: 'design_content',   \n");
          out.write("\t\t\t\t\t\t        \t    //这里可以选择自己需要的工具按钮名称,此处仅选择如下五个/*\n");
          out.write("\t\t\t\t\t\t        \t    toolbars: [[\n");
          out.write("\t\t\t\t\t\t        \t    'fullscreen', 'source', '|', 'undo', 'redo', '|',\n");
          out.write("\t\t\t\t\t\t        \t    'fontfamily', 'fontsize', '|', 'indent', '|',\n");
          out.write("\t\t\t\t\t\t        \t    'justifyleft', 'justifycenter', 'justifyright', 'justifyjustify', '|', \n");
          out.write("\t\t\t\t\t\t        \t    'inserttable', 'deletetable', 'insertparagraphbeforetable', 'insertrow', 'deleterow', '|',\n");
          out.write("\t\t\t\t\t\t        \t    ]],\n");
          out.write("\t\t\t\t\t\t        \t    wordCount:false,\n");
          out.write("\t\t\t\t\t\t        \t    elementPathEnabled:false,\n");
          out.write("\t\t\t\t\t\t        \t    initialFrameHeight:400\n");
          out.write("\t\t\t\t\t\t        \t});\n");
          out.write("\t\t\t\t\t\t\t </script>\n");
          out.write("\t\t\t\t\t\t\t<span class=\"Validform_checktip\"></span>\n");
          out.write("\t\t\t\t\t\t\t<label class=\"Validform_label\" style=\"display: none;\">通知公告内容</label>\n");
          out.write("\t\t\t\t\t\t</td>\n");
          out.write("\t\t\t\t</tr>\n");
          out.write("\t\t\t\t<tr>\n");
          out.write("\t\t\t\t\t<td align=\"right\">\n");
          out.write("\t\t\t\t\t\t<label class=\"Validform_label\">\n");
          out.write("\t\t\t\t\t\t\t类型:\n");
          out.write("\t\t\t\t\t\t</label>\n");
          out.write("\t\t\t\t\t</td>\n");
          out.write("\t\t\t\t\t<td class=\"value\">\n");
          out.write("\t\t\t\t\t     \t <input type=\"radio\" name=\"noticeType\" value=\"1\" datatype=\"*\"  />通知\n");
          out.write("         \t\t\t\t&nbsp;&nbsp;<input type=\"radio\" name=\"noticeType\" value=\"2\" checked=\"checked\" />公告\n");
          out.write("\t\t\t\t\t\t\t<span class=\"Validform_checktip\"></span>\n");
          out.write("\t\t\t\t\t\t\t<label class=\"Validform_label\" style=\"display: none;\">通知公告类型</label>\n");
          out.write("\t\t\t\t\t\t</td>\n");
          out.write("\t\t\t\t</tr>\n");
          out.write("\t\t\t\t<tr>\n");
          out.write("\t\t\t\t\t<td align=\"right\">\n");
          out.write("\t\t\t\t\t\t<label class=\"Validform_label\" style=\"white-space:nowrap;\">\n");
          out.write("\t\t\t\t\t\t\t授权级别:\n");
          out.write("\t\t\t\t\t\t</label>\n");
          out.write("\t\t\t\t\t</td>\n");
          out.write("\t\t\t\t\t<td class=\"value\">\n");
          out.write("\t\t\t\t\t     \t  <input type=\"radio\" name=\"noticeLevel\" value=\"1\" datatype=\"*\" checked=\"checked\" onclick=\"dataytpeSelect()\"/>全员\n");
          out.write("         \t\t\t\t&nbsp;&nbsp;<br/><input type=\"radio\" name=\"noticeLevel\" value=\"2\" onclick=\"dataytpeSelect('roleName')\"  />角色授权\n");
          out.write("\t\t\t\t\t\t<span id=\"roleName_span\" style=\"display: none\">\n");
          out.write("\t\t\t\t\t\t<input name=\"roleid\" name=\"roleid\" type=\"hidden\" value=\"\" id=\"roleid\">\n");
          out.write("\t\t\t\t\t\t<input name=\"roleName\" class=\"inputxt\" value=\"\" id=\"roleName\" readonly=\"readonly\"  />\n");
          out.write("\t\t\t\t\t\t");
          if (_jspx_meth_t_005fchoose_005f0(_jspx_th_t_005fformvalid_005f0, _jspx_page_context))
            return true;
          out.write("\n");
          out.write("\n");
          out.write("\t\t\t\t\t\t</span>\n");
          out.write("\t\t\t\t\t\t&nbsp;&nbsp;<br/><input type=\"radio\" name=\"noticeLevel\" value=\"3\" onclick=\"dataytpeSelect('userName')\"/>用户授权\n");
          out.write("\t\t\t\t\t\t<span id=\"userName_span\" style=\"display: none\">\n");
          out.write("\t\t\t\t\t\t<input name=\"userid\" name=\"userid\" type=\"hidden\" value=\"\" id=\"userid\">\n");
          out.write("\t\t\t\t\t\t<input name=\"userName\" class=\"inputxt\" value=\"\" id=\"userName\" readonly=\"readonly\" />\n");
          out.write("\t\t\t\t\t\t");
          if (_jspx_meth_t_005fchoose_005f1(_jspx_th_t_005fformvalid_005f0, _jspx_page_context))
            return true;
          out.write("\n");
          out.write("\t\t\t\t\t\t<span class=\"Validform_checktip\"></span>\n");
          out.write("\t\t\t\t\t\t\t<label class=\"Validform_label\" style=\"display: none;\">授权级别</label>\n");
          out.write("\t\t\t\t\t\t</td>\n");
          out.write("\t\t\t\t</tr>\n");
          out.write("\t\t\t\t<tr>\n");
          out.write("\t\t\t\t\t<td align=\"right\">\n");
          out.write("\t\t\t\t\t\t<label class=\"Validform_label\" style=\"white-space:nowrap;\">\n");
          out.write("\t\t\t\t\t\t\t阅读期限:\n");
          out.write("\t\t\t\t\t\t</label>\n");
          out.write("\t\t\t\t\t</td>\n");
          out.write("\t\t\t\t\t<td class=\"value\">\n");
          out.write("\t\t\t\t\t\t\t   <input id=\"noticeTerm\" name=\"noticeTerm\" type=\"text\" style=\"width: 150px\" \n");
          out.write("\t\t\t\t\t      \t\t\t\t\t\tclass=\"Wdate\" onClick=\"WdatePicker()\" >    \n");
          out.write("\t\t\t\t\t\t\t<span class=\"Validform_checktip\"></span>\n");
          out.write("\t\t\t\t\t\t\t<label class=\"Validform_label\" style=\"display: none;\">阅读期限</label>\n");
          out.write("\t\t\t\t\t\t</td>\n");
          out.write("\t\t\t\t</tr>\n");
          out.write("\t\t\t</table>\n");
          out.write("\t\t");
          int evalDoAfterBody = _jspx_th_t_005fformvalid_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_t_005fformvalid_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ft_005fformvalid_0026_005fusePlugin_005ftiptype_005flayout_005fformid_005fdialog_005fbeforeSubmit_005faction.reuse(_jspx_th_t_005fformvalid_005f0);
      _jspx_th_t_005fformvalid_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_t_005fformvalid_005f0, _jsp_getInstanceManager(), _jspx_th_t_005fformvalid_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_t_005fchoose_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_t_005fformvalid_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  t:choose
    org.jeecgframework.tag.core.easyui.ChooseTag _jspx_th_t_005fchoose_005f0 = (org.jeecgframework.tag.core.easyui.ChooseTag) _005fjspx_005ftagPool_005ft_005fchoose_0026_005furl_005ftitle_005ftextname_005fname_005fisclear_005fisInit_005ficon_005fhiddenid_005fhiddenName_005fnobody.get(org.jeecgframework.tag.core.easyui.ChooseTag.class);
    boolean _jspx_th_t_005fchoose_005f0_reused = false;
    try {
      _jspx_th_t_005fchoose_005f0.setPageContext(_jspx_page_context);
      _jspx_th_t_005fchoose_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_t_005fformvalid_005f0);
      // /webpage/system/notice/tSNotice-add.jsp(104,6) name = hiddenName type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_t_005fchoose_005f0.setHiddenName("roleid");
      // /webpage/system/notice/tSNotice-add.jsp(104,6) name = hiddenid type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_t_005fchoose_005f0.setHiddenid("id");
      // /webpage/system/notice/tSNotice-add.jsp(104,6) name = url type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_t_005fchoose_005f0.setUrl("userController.do?roles");
      // /webpage/system/notice/tSNotice-add.jsp(104,6) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_t_005fchoose_005f0.setName("roleList");
      // /webpage/system/notice/tSNotice-add.jsp(104,6) name = icon type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_t_005fchoose_005f0.setIcon("icon-search");
      // /webpage/system/notice/tSNotice-add.jsp(104,6) name = title type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_t_005fchoose_005f0.setTitle("common.role.list");
      // /webpage/system/notice/tSNotice-add.jsp(104,6) name = textname type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_t_005fchoose_005f0.setTextname("roleName");
      // /webpage/system/notice/tSNotice-add.jsp(104,6) name = isclear type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_t_005fchoose_005f0.setIsclear(new java.lang.Boolean(true));
      // /webpage/system/notice/tSNotice-add.jsp(104,6) name = isInit type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_t_005fchoose_005f0.setIsInit(new java.lang.Boolean(true));
      int _jspx_eval_t_005fchoose_005f0 = _jspx_th_t_005fchoose_005f0.doStartTag();
      if (_jspx_th_t_005fchoose_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ft_005fchoose_0026_005furl_005ftitle_005ftextname_005fname_005fisclear_005fisInit_005ficon_005fhiddenid_005fhiddenName_005fnobody.reuse(_jspx_th_t_005fchoose_005f0);
      _jspx_th_t_005fchoose_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_t_005fchoose_005f0, _jsp_getInstanceManager(), _jspx_th_t_005fchoose_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_t_005fchoose_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_t_005fformvalid_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  t:choose
    org.jeecgframework.tag.core.easyui.ChooseTag _jspx_th_t_005fchoose_005f1 = (org.jeecgframework.tag.core.easyui.ChooseTag) _005fjspx_005ftagPool_005ft_005fchoose_0026_005furl_005ftitle_005ftextname_005fname_005fisclear_005fisInit_005ficon_005fhiddenid_005fhiddenName_005fnobody.get(org.jeecgframework.tag.core.easyui.ChooseTag.class);
    boolean _jspx_th_t_005fchoose_005f1_reused = false;
    try {
      _jspx_th_t_005fchoose_005f1.setPageContext(_jspx_page_context);
      _jspx_th_t_005fchoose_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_t_005fformvalid_005f0);
      // /webpage/system/notice/tSNotice-add.jsp(112,6) name = hiddenName type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_t_005fchoose_005f1.setHiddenName("userid");
      // /webpage/system/notice/tSNotice-add.jsp(112,6) name = hiddenid type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_t_005fchoose_005f1.setHiddenid("id");
      // /webpage/system/notice/tSNotice-add.jsp(112,6) name = url type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_t_005fchoose_005f1.setUrl("noticeAuthorityUserController.do?selectUser");
      // /webpage/system/notice/tSNotice-add.jsp(112,6) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_t_005fchoose_005f1.setName("userList");
      // /webpage/system/notice/tSNotice-add.jsp(112,6) name = icon type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_t_005fchoose_005f1.setIcon("icon-search");
      // /webpage/system/notice/tSNotice-add.jsp(112,6) name = title type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_t_005fchoose_005f1.setTitle("common.user.list");
      // /webpage/system/notice/tSNotice-add.jsp(112,6) name = textname type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_t_005fchoose_005f1.setTextname("userName");
      // /webpage/system/notice/tSNotice-add.jsp(112,6) name = isclear type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_t_005fchoose_005f1.setIsclear(new java.lang.Boolean(true));
      // /webpage/system/notice/tSNotice-add.jsp(112,6) name = isInit type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_t_005fchoose_005f1.setIsInit(new java.lang.Boolean(true));
      int _jspx_eval_t_005fchoose_005f1 = _jspx_th_t_005fchoose_005f1.doStartTag();
      if (_jspx_th_t_005fchoose_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ft_005fchoose_0026_005furl_005ftitle_005ftextname_005fname_005fisclear_005fisInit_005ficon_005fhiddenid_005fhiddenName_005fnobody.reuse(_jspx_th_t_005fchoose_005f1);
      _jspx_th_t_005fchoose_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_t_005fchoose_005f1, _jsp_getInstanceManager(), _jspx_th_t_005fchoose_005f1_reused);
    }
    return false;
  }
}
